"""
SCPs Terraform Generation Module

Generates Terraform files for SCP deployment based on compliance analysis recommendations.
"""

import logging
from pathlib import Path
from typing import List

from .utils import make_safe_variable_name, write_terraform_file
from ..types import GroupedSCPRecommendations, OrganizationHierarchy, SCPPlacementRecommendations

# Set up logging
logger = logging.getLogger(__name__)


def _replace_account_id_in_arn(
    arn: str,
    organization_hierarchy: OrganizationHierarchy
) -> str:
    """
    Replace account ID in ARN with Terraform local variable reference.

    Args:
        arn: IAM user ARN (e.g., "arn:aws:iam::111111111111:user/path/username")
        organization_hierarchy: Organization structure for account ID lookups

    Returns:
        ARN with account ID replaced by local variable reference
        (e.g., "arn:aws:iam::${local.account_name_account_id}:user/path/username")
    """
    parts = arn.split(":")
    if len(parts) >= 5 and parts[0] == "arn" and parts[2] == "iam":
        account_id = parts[4]
        account_info = organization_hierarchy.accounts.get(account_id)
        if account_info:
            safe_account_name = make_safe_variable_name(account_info.account_name)
            parts[4] = f"${{local.{safe_account_name}_account_id}}"
            return ":".join(parts)
    return arn


def _build_scp_terraform_module(
    module_name: str,
    target_id_reference: str,
    recommendations: List[SCPPlacementRecommendations],
    comment: str,
    organization_hierarchy: OrganizationHierarchy
) -> str:
    """
    Build Terraform module call for SCP deployment.

    Args:
        module_name: Name of the Terraform module instance (e.g., "scps_root")
        target_id_reference: Reference to the target ID (e.g., "local.root_ou_id")
        recommendations: List of SCP placement recommendations for this target
        comment: Comment line describing the configuration (e.g., "Organization Root")
        organization_hierarchy: Organization structure for account ID lookups

    Returns:
        Complete Terraform module block as a string
    """
    terraform_content = f'''# Auto-generated SCP Terraform configuration for {comment}
# Generated by Headroom based on compliance analysis

module "{module_name}" {{
  source = "../modules/scps"
  target_id = {target_id_reference}

'''

    # Collect enabled checks
    enabled_checks = set()
    for rec in recommendations:
        if rec.compliance_percentage == 100.0:
            check_name_terraform = rec.check_name.replace("-", "_")
            enabled_checks.add(check_name_terraform)

    # EC2
    terraform_content += "  # EC2\n"
    deny_imds_v1_ec2 = "deny_imds_v1_ec2" in enabled_checks
    terraform_content += f"  deny_imds_v1_ec2 = {str(deny_imds_v1_ec2).lower()}\n"
    terraform_content += "\n"

    # EKS
    terraform_content += "  # EKS\n"
    deny_eks_create_cluster_without_tag = "deny_eks_create_cluster_without_tag" in enabled_checks
    terraform_content += f"  deny_eks_create_cluster_without_tag = {str(deny_eks_create_cluster_without_tag).lower()}\n"
    terraform_content += "\n"

    # IAM
    terraform_content += "  # IAM\n"
    deny_iam_user_creation = "deny_iam_user_creation" in enabled_checks
    terraform_content += f"  deny_iam_user_creation = {str(deny_iam_user_creation).lower()}\n"

    if deny_iam_user_creation:
        # Get IAM user ARNs from recommendations
        allowed_iam_user_arns = []
        for rec in recommendations:
            if rec.check_name.replace("-", "_") == "deny_iam_user_creation" and rec.allowed_iam_user_arns:
                allowed_iam_user_arns = rec.allowed_iam_user_arns
                break

        if allowed_iam_user_arns:
            terraform_content += "  allowed_iam_users = [\n"
            for arn in allowed_iam_user_arns:
                transformed_arn = _replace_account_id_in_arn(arn, organization_hierarchy)
                terraform_content += f'    "{transformed_arn}",\n'
            terraform_content += "  ]\n"
        else:
            terraform_content += "  allowed_iam_users = []\n"

    terraform_content += "\n"

    # RDS
    terraform_content += "  # RDS\n"
    deny_rds_unencrypted = "deny_rds_unencrypted" in enabled_checks
    terraform_content += f"  deny_rds_unencrypted = {str(deny_rds_unencrypted).lower()}\n"

    terraform_content += "}\n"
    return terraform_content


def _generate_account_scp_terraform(
    account_id: str,
    account_recs: List[SCPPlacementRecommendations],
    organization_hierarchy: OrganizationHierarchy,
    output_path: Path
) -> None:
    """
    Generate Terraform file for account-level SCPs.

    Args:
        account_id: AWS account ID
        account_recs: List of SCP recommendations for this account
        organization_hierarchy: Organization structure information
        output_path: Directory to write Terraform files to
    """
    account_info = organization_hierarchy.accounts.get(account_id)
    if not account_info:
        raise RuntimeError(f"Account ({account_id}) not found in organization hierarchy")

    # Convert account name to terraform-friendly format
    account_name = make_safe_variable_name(account_info.account_name)
    filename = f"{account_name}_scps.tf"
    filepath = output_path / filename

    # Generate Terraform content
    terraform_content = _build_scp_terraform_module(
        module_name=f"scps_{account_name}",
        target_id_reference=f"local.{account_name}_account_id",
        recommendations=account_recs,
        comment=account_info.account_name,
        organization_hierarchy=organization_hierarchy
    )

    # Write the file
    write_terraform_file(filepath, terraform_content, "SCP")


def _generate_ou_scp_terraform(
    ou_id: str,
    ou_recs: List[SCPPlacementRecommendations],
    organization_hierarchy: OrganizationHierarchy,
    output_path: Path
) -> None:
    """
    Generate Terraform file for OU-level SCPs.

    Args:
        ou_id: Organizational Unit ID
        ou_recs: List of SCP recommendations for this OU
        organization_hierarchy: Organization structure information
        output_path: Directory to write Terraform files to
    """
    ou_info = organization_hierarchy.organizational_units.get(ou_id)
    if not ou_info:
        raise RuntimeError(f"OU {ou_id} not found in organization hierarchy")

    # Convert OU name to terraform-friendly format
    ou_name = make_safe_variable_name(ou_info.name)
    filename = f"{ou_name}_ou_scps.tf"
    filepath = output_path / filename

    # Generate Terraform content
    terraform_content = _build_scp_terraform_module(
        module_name=f"scps_{ou_name}_ou",
        target_id_reference=f"local.top_level_{ou_name}_ou_id",
        recommendations=ou_recs,
        comment=f"OU {ou_info.name}",
        organization_hierarchy=organization_hierarchy
    )

    # Write the file
    write_terraform_file(filepath, terraform_content, "SCP")


def _generate_root_scp_terraform(
    root_recommendations: List[SCPPlacementRecommendations],
    organization_hierarchy: OrganizationHierarchy,
    output_path: Path
) -> None:
    """
    Generate Terraform file for root-level SCPs.

    Args:
        root_recommendations: List of SCP recommendations for the root level
        organization_hierarchy: Organization structure information
        output_path: Directory to write Terraform files to
    """
    if not root_recommendations:
        return

    filename = "root_scps.tf"
    filepath = output_path / filename

    # Generate Terraform content
    terraform_content = _build_scp_terraform_module(
        module_name="scps_root",
        target_id_reference="local.root_ou_id",
        recommendations=root_recommendations,
        comment="Organization Root",
        organization_hierarchy=organization_hierarchy
    )

    # Write the file
    write_terraform_file(filepath, terraform_content, "SCP")


def generate_scp_terraform(
    recommendations: List[SCPPlacementRecommendations],
    organization_hierarchy: OrganizationHierarchy,
    output_dir: str = "test_environment/scps"
) -> None:
    """
    Generate Terraform files for SCP deployment based on recommendations.

    Args:
        recommendations: List of SCP placement recommendations
        organization_hierarchy: Organization structure information
        output_dir: Directory to write Terraform files to
    """
    if not recommendations:
        return

    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    # Group recommendations by level and target
    account_recommendations: GroupedSCPRecommendations = {}
    ou_recommendations: GroupedSCPRecommendations = {}
    root_recommendations: List[SCPPlacementRecommendations] = []

    for rec in recommendations:
        if rec.recommended_level == "account":
            for account_id in rec.affected_accounts:
                if account_id not in account_recommendations:
                    account_recommendations[account_id] = []
                account_recommendations[account_id].append(rec)
        elif rec.recommended_level == "ou" and rec.target_ou_id:
            if rec.target_ou_id not in ou_recommendations:
                ou_recommendations[rec.target_ou_id] = []
            ou_recommendations[rec.target_ou_id].append(rec)
        elif rec.recommended_level == "root":
            root_recommendations.append(rec)

    # Generate Terraform files for each account
    for account_id, account_recs in account_recommendations.items():
        _generate_account_scp_terraform(account_id, account_recs, organization_hierarchy, output_path)

    # Generate Terraform files for each OU
    for ou_id, ou_recs in ou_recommendations.items():
        _generate_ou_scp_terraform(ou_id, ou_recs, organization_hierarchy, output_path)

    # Generate Terraform file for root level
    _generate_root_scp_terraform(root_recommendations, organization_hierarchy, output_path)
