"""
Organization Info Terraform Generation Module

Generates Terraform configuration files for AWS Organizations structure data
to support SCP/RCP deployment targeting.
"""

import logging
from pathlib import Path
from typing import Dict, List

from boto3.session import Session

from .utils import make_safe_variable_name
from ..aws.organization import analyze_organization_structure
from ..types import OrganizationHierarchy, OrganizationalUnit, AccountOrgPlacement

# Set up logging
logger = logging.getLogger(__name__)


def generate_terraform_org_info(session: Session, output_path: str) -> None:
    """
    Generate grab_org_info.tf file with organization structure data sources.

    Args:
        session: AWS session with Organizations API access
        output_path: Path to write the Terraform file

    Raises:
        RuntimeError: If organization structure analysis fails
        IOError: If file write fails
    """
    logger.info("Generating Terraform organization info file")

    organization_hierarchy = analyze_organization_structure(session)
    logger.info(f"Found {len(organization_hierarchy.organizational_units)} OUs and {len(organization_hierarchy.accounts)} accounts")

    # Generate Terraform content
    terraform_content = _generate_terraform_content(organization_hierarchy)

    # Write to file
    output_file = Path(output_path)
    output_file.parent.mkdir(parents=True, exist_ok=True)

    with open(output_file, 'w') as f:
        f.write(terraform_content)
    logger.info(f"Successfully generated Terraform file: {output_path}")


def _generate_terraform_header() -> List[str]:
    """
    Generate file header and root OU data source.

    Returns:
        List of Terraform configuration lines for file header
    """
    return [
        "# Auto-generated Terraform configuration for AWS Organizations structure",
        "# Generated by Headroom for SCP/RCP deployment targeting",
        "",
        "# Get the root OU ID",
        'data "aws_organizations_organization" "org" {}',
        "",
        'data "aws_organizations_organizational_units" "root_ou" {',
        "  parent_id = data.aws_organizations_organization.org.roots[0].id",
        "}",
        "",
        "# Get accounts for each top-level OU",
    ]


def _generate_ou_data_sources(
    organizational_units: Dict[str, OrganizationalUnit]
) -> List[str]:
    """
    Generate data sources for each top-level OU's child accounts.

    Args:
        organizational_units: All OUs in the organization

    Returns:
        List of Terraform data source blocks
    """
    content_parts: List[str] = []

    if organizational_units:
        top_level_ous = [
            ou for ou in organizational_units.values()
            if ou.parent_ou_id is None
        ]

        for ou in top_level_ous:
            safe_name = make_safe_variable_name(ou.name)
            content_parts.extend([
                f'data "aws_organizations_organizational_unit_child_accounts" "{safe_name}_accounts" {{',
                "  parent_id = [",
                "    for ou in data.aws_organizations_organizational_units.root_ou.children :",
                f"    ou.id if ou.name == \"{ou.name}\"",
                "  ][0]",
                "}",
                "",
            ])

    return content_parts


def _generate_root_locals() -> List[str]:
    """
    Generate opening of locals block with root validation check.

    Returns:
        List of Terraform lines for locals block opening with root_ou_id
    """
    return [
        "locals {",
        "  # Validation check for root OU access",
        "  validation_check_root = (length(data.aws_organizations_organization.org.roots) == 1) ? \"All good. This is a no-op.\" : error(\"[Error] Expected exactly 1 root OU, found ${length(data.aws_organizations_organization.org.roots)}\")",
        "",
        "  # Root OU ID",
        "  root_ou_id = data.aws_organizations_organization.org.roots[0].id",
        "",
    ]


def _generate_ou_locals(
    organizational_units: Dict[str, OrganizationalUnit]
) -> List[str]:
    """
    Generate local variables for OU IDs.

    Args:
        organizational_units: All OUs in the organization

    Returns:
        List of Terraform lines for OU local variables with validations
    """
    content_parts: List[str] = []

    if organizational_units:
        top_level_ous = [
            ou for ou in organizational_units.values()
            if ou.parent_ou_id is None
        ]

        if top_level_ous:
            content_parts.extend([
                "  # Top-level OU IDs by name",
            ])

            for ou in top_level_ous:
                safe_name = make_safe_variable_name(ou.name)
                content_parts.extend([
                    f"  # Validation for {ou.name} OU",
                    f"  validation_check_{safe_name}_ou = (length([for ou in data.aws_organizations_organizational_units.root_ou.children : ou.id if ou.name == \"{ou.name}\"]) == 1) ? \"All good. This is a no-op.\" : error(\"[Error] Expected exactly 1 {ou.name} OU, found ${{length([for ou in data.aws_organizations_organizational_units.root_ou.children : ou.id if ou.name == \"{ou.name}\"])}}\")",
                    "",
                    f"  top_level_{safe_name}_ou_id = [",
                    "    for ou in data.aws_organizations_organizational_units.root_ou.children :",
                    f"    ou.id if ou.name == \"{ou.name}\"",
                    "  ][0]",
                    "",
                ])

    return content_parts


def _group_accounts_by_top_level_ou(
    accounts: Dict[str, AccountOrgPlacement],
    organizational_units: Dict[str, OrganizationalUnit]
) -> Dict[str, List[AccountOrgPlacement]]:
    """
    Group accounts by their top-level parent OU.

    Walks the OU hierarchy for each account to find which top-level OU
    (direct child of root) the account belongs to.

    Args:
        accounts: All accounts in the organization
        organizational_units: All OUs (needed for hierarchy traversal)

    Returns:
        Dictionary mapping top-level OU ID -> list of accounts under that OU
    """
    accounts_by_top_level_ou: Dict[str, List[AccountOrgPlacement]] = {}

    for account in accounts.values():
        top_level_ou_id = account.parent_ou_id
        current_ou_id = account.parent_ou_id

        # Walk up the OU hierarchy to find the top-level parent
        while current_ou_id in organizational_units:
            current_ou = organizational_units[current_ou_id]
            if current_ou.parent_ou_id is None:
                # This is a top-level OU (direct child of root)
                top_level_ou_id = current_ou_id
                break
            current_ou_id = current_ou.parent_ou_id

        # Group account under its top-level OU
        if top_level_ou_id not in accounts_by_top_level_ou:
            accounts_by_top_level_ou[top_level_ou_id] = []
        accounts_by_top_level_ou[top_level_ou_id].append(account)

    return accounts_by_top_level_ou


def _generate_account_locals(
    accounts: Dict[str, AccountOrgPlacement],
    organizational_units: Dict[str, OrganizationalUnit]
) -> List[str]:
    """
    Generate local variables for account IDs.

    Args:
        accounts: All accounts in the organization
        organizational_units: All OUs (for name lookups)

    Returns:
        List of Terraform lines for account local variables with validations
    """
    content_parts: List[str] = []

    if not accounts:
        return content_parts

    content_parts.extend([
        "  # Account IDs by name",
    ])

    # Data preparation: group accounts by top-level OU
    accounts_by_top_level_ou = _group_accounts_by_top_level_ou(
        accounts,
        organizational_units
    )

    # Code generation: build Terraform locals for each account
    for top_level_ou_id, accounts_list in accounts_by_top_level_ou.items():
        if top_level_ou_id not in organizational_units:
            continue

        ou_name = organizational_units[top_level_ou_id].name
        safe_ou_name = make_safe_variable_name(ou_name)

        for account in accounts_list:
            safe_account_name = make_safe_variable_name(account.account_name)
            content_parts.extend([
                f"  # Validation for {account.account_name} account",
                f"  validation_check_{safe_account_name}_account = (length([for account in data.aws_organizations_organizational_unit_child_accounts.{safe_ou_name}_accounts.accounts : account.id if account.name == \"{account.account_name}\"]) == 1) ? \"All good. This is a no-op.\" : error(\"[Error] Expected exactly 1 {account.account_name} account, found ${{length([for account in data.aws_organizations_organizational_unit_child_accounts.{safe_ou_name}_accounts.accounts : account.id if account.name == \"{account.account_name}\"])}}\")",
                "",
                f"  {safe_account_name}_account_id = [",
                f"    for account in data.aws_organizations_organizational_unit_child_accounts.{safe_ou_name}_accounts.accounts :",
                f"    account.id if account.name == \"{account.account_name}\"",
                "  ][0]",
                "",
            ])

    return content_parts


def _generate_terraform_content(organization_hierarchy: OrganizationHierarchy) -> str:
    """
    Generate Terraform content with data sources derived from root_ou, no hardcoded IDs.

    Args:
        organization_hierarchy: Organization structure data from analyze_organization_structure()

    Returns:
        Complete Terraform configuration as string
    """
    content_parts = []

    content_parts.extend(_generate_terraform_header())

    content_parts.extend(
        _generate_ou_data_sources(organization_hierarchy.organizational_units)
    )

    content_parts.extend(_generate_root_locals())

    content_parts.extend(
        _generate_ou_locals(organization_hierarchy.organizational_units)
    )

    content_parts.extend(
        _generate_account_locals(
            organization_hierarchy.accounts,
            organization_hierarchy.organizational_units
        )
    )

    content_parts.append("}")

    return "\n".join(content_parts) + "\n"
