"""
Terraform data models for structured representation.

Separates Terraform structure from rendering logic for better testability.
"""

from dataclasses import dataclass
from typing import Any, List, Union


@dataclass
class TerraformParameter:
    """
    Single parameter in a Terraform module.

    Attributes:
        key: Parameter name
        value: Parameter value (bool, str, list, or other type)
    """

    key: str
    value: Any

    def render(self) -> str:
        """
        Render parameter as HCL.

        Returns:
            HCL-formatted parameter string with proper indentation
        """
        if isinstance(self.value, bool):
            return f"  {self.key} = {str(self.value).lower()}"
        if isinstance(self.value, list):
            if not self.value:
                return f"  {self.key} = []"
            items = [f'    "{item}",' for item in self.value]
            return f"  {self.key} = [\n" + "\n".join(items) + "\n  ]"
        if isinstance(self.value, str):
            return f'  {self.key} = "{self.value}"'
        return f"  {self.key} = {self.value}"


@dataclass
class TerraformComment:
    """
    Comment line in a Terraform module.

    Used for section headers and explanatory comments within module blocks.
    Empty text creates a blank line for spacing.

    Attributes:
        text: Comment text (without the # prefix). Empty string creates blank line.
    """

    text: str

    def render(self) -> str:
        """
        Render comment as HCL.

        Returns:
            HCL-formatted comment string with proper indentation, or empty string for blank lines
        """
        if self.text:
            return f"  # {self.text}"
        return ""


TerraformElement = Union[TerraformParameter, TerraformComment]


@dataclass
class TerraformModule:
    """
    Structured representation of Terraform module.

    Attributes:
        name: Module instance name
        source: Module source path
        target_id: Target resource identifier
        parameters: List of module parameters and comments
        comment: Optional comment describing the module
        policy_type: Type of policy (SCP or RCP) for comment generation
    """

    name: str
    source: str
    target_id: str
    parameters: List[TerraformElement]
    comment: str = ""
    policy_type: str = "SCP"

    def render(self) -> str:
        """
        Render module as Terraform HCL.

        Returns:
            Complete Terraform module block as string
        """
        lines = []

        if self.comment:
            lines.append(f"# Auto-generated {self.policy_type} Terraform configuration for {self.comment}")
            if self.policy_type == "RCP":
                lines.append("# Generated by Headroom based on third-party account analysis")
            else:
                lines.append("# Generated by Headroom based on compliance analysis")
            lines.append("")

        lines.extend([
            f'module "{self.name}" {{',
            f'  source = "{self.source}"',
            f'  target_id = {self.target_id}',
            ""
        ])

        for element in self.parameters:
            lines.append(element.render())

        lines.append("}")
        return "\n".join(lines) + "\n"
