"""
Terraform data models for structured representation.

Separates Terraform structure from rendering logic for better testability.
"""

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, TypeAlias

from ..constants import GENERATED_MARKER

TerraformScalarValue: TypeAlias = bool | int | float | str
TerraformListValue: TypeAlias = list[str]
TerraformValue: TypeAlias = TerraformScalarValue | TerraformListValue

# Everything one run means the output directory to hold, rendered but not yet
# written. Building the whole plan before touching disk is what keeps a failure
# partway through generation from leaving half of the previous output replaced.
TerraformPlan: TypeAlias = Dict[Path, str]

# Everything one renderer means its output directory to hold, keyed by
# destination path. Rendered, not yet written, and not yet the whole run's
# plan -- the compiler merges the three renderers' output into that.
RenderedTerraformFiles: TypeAlias = Dict[Path, str]


@dataclass
class TerraformParameter:
    """
    Single parameter in a Terraform module.

    Attributes:
        key: Parameter name
        value: Parameter value (bool, str, list, or other type)
    """
    key: str
    value: TerraformValue

    def render(self) -> str:
        """
        Render parameter as HCL.

        Returns:
            HCL-formatted parameter string with proper indentation
        """
        if isinstance(self.value, bool):
            return f"  {self.key} = {str(self.value).lower()}"
        if isinstance(self.value, list):
            if not self.value:
                return f"  {self.key} = []"
            items = [f'    "{item}",' for item in self.value]
            return f"  {self.key} = [\n" + "\n".join(items) + "\n  ]"
        if isinstance(self.value, str):
            return f'  {self.key} = "{self.value}"'
        return f"  {self.key} = {self.value}"


@dataclass
class TerraformComment:
    """
    Comment line in a Terraform module.

    Used for section headers and explanatory comments within module blocks.
    Empty text creates a blank line for spacing.

    Attributes:
        text: Comment text (without the # prefix). Empty string creates blank line.
    """
    text: str

    def render(self) -> str:
        """
        Render comment as HCL.

        Returns:
            HCL-formatted comment string with proper indentation, or empty string for blank lines
        """
        if self.text:
            return f"  # {self.text}"
        return ""


TerraformElement: TypeAlias = TerraformParameter | TerraformComment


@dataclass
class TerraformModule:
    """
    Structured representation of Terraform module.

    Attributes:
        name: Module instance name
        source: Module source path
        target_id: Target resource identifier
        parameters: List of module parameters and comments
        comment: Optional comment describing the module
        policy_type: Type of policy (SCP or RCP) for comment generation
    """
    name: str
    source: str
    target_id: str
    parameters: list[TerraformElement]
    comment: str = ""
    policy_type: str = "SCP"

    def render(self) -> str:
        """
        Render module as Terraform HCL.

        Returns:
            Complete Terraform module block as string
        """
        # Unconditional, and first: reconciliation identifies its own output by
        # this exact line, so a file rendered without it can never be cleaned up.
        lines: list[str] = [GENERATED_MARKER]

        if self.comment:
            lines.append(f"# Auto-generated {self.policy_type} Terraform configuration for {self.comment}")
            if self.policy_type == "RCP":
                lines.append("# Generated by Headroom based on third-party account analysis")
            else:
                lines.append("# Generated by Headroom based on compliance analysis")
        lines.append("")

        lines.extend([
            f'module "{self.name}" {{',
            f'  source = "{self.source}"',
            f'  target_id = {self.target_id}',
            ""
        ])

        for element in self.parameters:
            lines.append(element.render())

        lines.append("}")
        return "\n".join(lines) + "\n"
