"""
Tests for terraform.plan: the pure renderers and the whole-run compiler.

Rendering happens in full, and is validated in full, before anything reaches
the filesystem. These tests pin that the rendering half touches nothing.
"""

from pathlib import Path

from headroom.terraform.generate_org_info import render_terraform_org_info
from headroom.terraform.generate_rcps import render_rcp_terraform
from headroom.terraform.generate_scps import render_scp_terraform
from headroom.types import (
    AccountOrgPlacement,
    OrganizationHierarchy,
    OrganizationalUnit,
    RCPPlacementRecommendations,
    SCPPlacementRecommendations,
)


def org_with_one_ou() -> OrganizationHierarchy:
    """One OU holding one account, enough to render at every level."""
    return OrganizationHierarchy(
        root_id="r-1111",
        organizational_units={
            "ou-1111-11111111": OrganizationalUnit(
                ou_id="ou-1111-11111111",
                name="Test OU",
                parent_ou_id="r-1111",
                child_ous=[],
                accounts=["111111111111"],
            )
        },
        accounts={
            "111111111111": AccountOrgPlacement(
                account_id="111111111111",
                account_name="payments",
                parent_ou_id="ou-1111-11111111",
                ou_path=["r-1111", "ou-1111-11111111"],
            )
        },
    )


def scp_rec(level: str = "root") -> SCPPlacementRecommendations:
    return SCPPlacementRecommendations(
        check_name="deny-ec2-imds-v1",
        recommended_level=level,
        target_ou_id=None,
        affected_accounts=[],
        compliance_percentage=100.0,
        reasoning="test",
    )


def rcp_rec(level: str = "root") -> RCPPlacementRecommendations:
    return RCPPlacementRecommendations(
        check_name="deny-sts-third-party-assumerole",
        recommended_level=level,
        target_ou_id=None,
        affected_accounts=[],
        third_party_account_ids=[],
        reasoning="test",
    )


def test_render_scp_terraform_does_not_create_its_output_directory(
    tmp_path: Path
) -> None:
    absent = tmp_path / "scps"

    rendered = render_scp_terraform([scp_rec()], org_with_one_ou(), absent)

    assert not absent.exists()
    assert set(rendered) == {absent / "root_scps.tf"}


def test_render_rcp_terraform_does_not_create_its_output_directory(
    tmp_path: Path
) -> None:
    absent = tmp_path / "rcps"

    rendered = render_rcp_terraform([rcp_rec()], org_with_one_ou(), absent)

    assert not absent.exists()
    assert set(rendered) == {absent / "root_rcps.tf"}


def test_render_terraform_org_info_returns_content_and_writes_nothing(
    tmp_path: Path
) -> None:
    content = render_terraform_org_info(org_with_one_ou())

    assert content.splitlines()[0] == "# Code generated by Headroom. DO NOT EDIT."
    assert not any(tmp_path.iterdir())
