"""
Tests for terraform.plan: the pure renderers and the whole-run compiler.

Rendering happens in full, and is validated in full, before anything reaches
the filesystem. These tests pin that the rendering half touches nothing.
"""

import os
from pathlib import Path
from typing import Dict, List

import pytest

from headroom.config import AccountTagLayout, HeadroomConfig
from headroom.constants import GENERATED_MARKER
from headroom.terraform.generate_org_info import render_terraform_org_info
from headroom.terraform.generate_rcps import render_rcp_terraform
from headroom.terraform.generate_scps import render_scp_terraform
from headroom.terraform.models import RenderedTerraformFiles
from headroom.terraform.plan import TerraformPlan, compile_terraform_plan, _validate_plan
from headroom.types import (
    AccountOrgPlacement,
    OrganizationHierarchy,
    OrganizationalUnit,
    RCPPlacementRecommendations,
    SCPPlacementRecommendations,
)


def org_with_one_ou() -> OrganizationHierarchy:
    """One OU holding one account, enough to render at every level."""
    return OrganizationHierarchy(
        root_id="r-1111",
        organizational_units={
            "ou-1111-11111111": OrganizationalUnit(
                ou_id="ou-1111-11111111",
                name="Test OU",
                parent_ou_id="r-1111",
                child_ous=[],
                accounts=["111111111111"],
            )
        },
        accounts={
            "111111111111": AccountOrgPlacement(
                account_id="111111111111",
                account_name="payments",
                parent_ou_id="ou-1111-11111111",
                ou_path=["r-1111", "ou-1111-11111111"],
            )
        },
    )


def scp_rec(level: str = "root") -> SCPPlacementRecommendations:
    return SCPPlacementRecommendations(
        check_name="deny-ec2-imds-v1",
        recommended_level=level,
        target_ou_id=None,
        affected_accounts=[],
        compliance_percentage=100.0,
        reasoning="test",
    )


def rcp_rec(level: str = "root") -> RCPPlacementRecommendations:
    return RCPPlacementRecommendations(
        check_name="deny-sts-third-party-assumerole",
        recommended_level=level,
        target_ou_id=None,
        affected_accounts=[],
        third_party_account_ids=[],
        reasoning="test",
    )


def test_render_scp_terraform_does_not_create_its_output_directory(
    tmp_path: Path
) -> None:
    absent = tmp_path / "scps"

    rendered = render_scp_terraform([scp_rec()], org_with_one_ou(), absent)

    assert not absent.exists()
    assert set(rendered) == {absent / "root_scps.tf"}


def test_render_rcp_terraform_does_not_create_its_output_directory(
    tmp_path: Path
) -> None:
    absent = tmp_path / "rcps"

    rendered = render_rcp_terraform([rcp_rec()], org_with_one_ou(), absent)

    assert not absent.exists()
    assert set(rendered) == {absent / "root_rcps.tf"}


def test_render_terraform_org_info_returns_content_and_writes_nothing(
    tmp_path: Path
) -> None:
    content = render_terraform_org_info(org_with_one_ou())

    assert content.splitlines()[0] == "# Code generated by Headroom. DO NOT EDIT."
    assert not any(tmp_path.iterdir())


def config_for(tmp_path: Path, scps: str = "scps", rcps: str = "rcps") -> HeadroomConfig:
    return HeadroomConfig(
        management_account_id="111111111111",
        use_account_name_from_tags=False,
        account_tag_layout=AccountTagLayout(
            environment="Env", name="Name", owner="Owner"
        ),
        scps_dir=str(tmp_path / scps),
        rcps_dir=str(tmp_path / rcps),
    )


def test_compile_covers_org_info_both_policy_files_the_link_and_both_dirs(
    tmp_path: Path
) -> None:
    plan = compile_terraform_plan(
        config_for(tmp_path), org_with_one_ou(), [scp_rec()], [rcp_rec()]
    )

    scps = Path(os.path.abspath(tmp_path / "scps"))
    rcps = Path(os.path.abspath(tmp_path / "rcps"))

    assert set(plan.files) == {
        scps / "grab_org_info.tf",
        scps / "root_scps.tf",
        rcps / "root_rcps.tf",
    }
    assert plan.symlinks == {rcps / "grab_org_info.tf": "../scps/grab_org_info.tf"}
    assert plan.managed_directories == (scps, rcps)


def test_compile_writes_nothing(tmp_path: Path) -> None:
    compile_terraform_plan(
        config_for(tmp_path), org_with_one_ou(), [scp_rec()], [rcp_rec()]
    )

    assert not (tmp_path / "scps").exists()
    assert not (tmp_path / "rcps").exists()


def test_two_spellings_of_one_directory_are_rejected_before_the_collision(
    tmp_path: Path
) -> None:
    """
    Equal managed directories are named as the cause, not as a symptom.

    Pointing scps_dir and rcps_dir at one directory also makes the org-info
    file and the reserved symlink claim one path. That collision is real, but
    reporting it would send the operator looking for a naming clash instead of
    at the two configuration values that caused it.
    """
    config = HeadroomConfig(
        management_account_id="111111111111",
        use_account_name_from_tags=False,
        account_tag_layout=AccountTagLayout(
            environment="Env", name="Name", owner="Owner"
        ),
        scps_dir=str(tmp_path / "out"),
        rcps_dir=str(tmp_path / "sub" / ".." / "out"),
    )

    with pytest.raises(RuntimeError, match="same directory"):
        compile_terraform_plan(config, org_with_one_ou(), [scp_rec()], [rcp_rec()])


def _scp_render_colliding_with_org_info(
    recommendations: List[SCPPlacementRecommendations],
    organization_hierarchy: OrganizationHierarchy,
    output_path: Path,
) -> RenderedTerraformFiles:
    """Stand-in for render_scp_terraform: claims grab_org_info.tf too."""
    return {output_path / "grab_org_info.tf": f"{GENERATED_MARKER}\n"}


def test_two_components_claiming_one_destination_are_rejected(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """
    Reachable through the compiler's claim_plan_path merge.

    render_terraform_org_info and render_scp_terraform each keep their own
    namespace collision-free, but cannot see each other's, so only
    claim_plan_path -- not `files.update`, which would silently drop one --
    catches the two landing on one destination. Forcing the SCP renderer to
    emit grab_org_info.tf collides with the organization data sources the
    compiler always claims first.
    """
    monkeypatch.setattr(
        "headroom.terraform.plan.render_scp_terraform",
        _scp_render_colliding_with_org_info,
    )

    with pytest.raises(RuntimeError, match="claim"):
        compile_terraform_plan(
            config_for(tmp_path), org_with_one_ou(), [scp_rec()], [rcp_rec()]
        )


def _plan(tmp_path: Path, files: Dict[Path, str], symlinks: Dict[Path, str]) -> TerraformPlan:
    return TerraformPlan(
        managed_directories=(
            Path(os.path.abspath(tmp_path / "scps")),
            Path(os.path.abspath(tmp_path / "rcps")),
        ),
        files=files,
        symlinks=symlinks,
    )


def test_a_symlink_anywhere_but_the_reserved_path_is_rejected(tmp_path: Path) -> None:
    """
    Unreachable from any renderer; no renderer plans a symlink at all.

    Checked because the applier trusts plan.symlinks to name only the one link
    Headroom maintains, and would otherwise replace an operator's own link.
    """
    scps = Path(os.path.abspath(tmp_path / "scps"))
    plan = _plan(tmp_path, {}, {scps / "shortcut.tf": "../elsewhere.tf"})

    with pytest.raises(RuntimeError, match="only symlink Headroom maintains"):
        _validate_plan(plan)


def test_a_destination_outside_the_managed_directories_is_rejected(
    tmp_path: Path
) -> None:
    """
    Unreachable from any renderer; make_safe_variable_name leaves no path
    separator in a filename. Checked because it is the invariant that keeps a
    write or a delete from escaping the two directories Headroom owns.
    """
    scps = Path(os.path.abspath(tmp_path / "scps"))
    plan = _plan(
        tmp_path,
        {scps / ".." / "escaped.tf": f"{GENERATED_MARKER}\n"},
        {},
    )

    with pytest.raises(RuntimeError, match="outside the directories"):
        _validate_plan(plan)


def test_two_destinations_that_normalize_alike_are_rejected(tmp_path: Path) -> None:
    """
    Unreachable in production: within one directory filenames carry no
    separator, and across the two it needs equal managed directories, which is
    rejected first. Checked because Path folds '.' away but not '..', so two
    dict keys can be distinct and still name one file.
    """
    scps = Path(os.path.abspath(tmp_path / "scps"))
    plan = _plan(
        tmp_path,
        {
            scps / "root_scps.tf": f"{GENERATED_MARKER}\n",
            scps / "sub" / ".." / "root_scps.tf": f"{GENERATED_MARKER}\n",
        },
        {},
    )

    with pytest.raises(RuntimeError, match="Two destinations resolve to"):
        _validate_plan(plan)


def test_a_file_planned_without_the_marker_is_rejected(tmp_path: Path) -> None:
    """
    Unreachable from any renderer; every one stamps the marker first.
    Checked because a file written without it can never be recognized as
    Headroom's, so it would survive every future reconciliation.
    """
    scps = Path(os.path.abspath(tmp_path / "scps"))
    plan = _plan(tmp_path, {scps / "root_scps.tf": 'module "x" {}\n'}, {})

    with pytest.raises(RuntimeError, match="does not open with"):
        _validate_plan(plan)
