"""
Tests for terraform.generate_scps module.

Covers registry-driven rendering and the rejection of a recommendation for an
unregistered check, alongside the early returns, the aborts on missing
targets, and the filename collisions the plan aborts on.
"""

from pathlib import Path
from typing import List, Optional, Sequence

import pytest

from headroom.types import (
    AccountOrgPlacement,
    OrganizationHierarchy,
    OrganizationalUnit,
    SCPPlacementRecommendations,
)
from headroom.checks.registry import (
    _CHECK_REGISTRY,
    Allowlist,
    CheckDefinition,
    get_check_definitions,
    get_check_names,
)
from headroom.checks.scps.deny_ec2_public_ip import DenyEc2PublicIpCheck
from headroom.enums import TerraformSection
from headroom.terraform import make_safe_variable_name
from headroom.terraform.generate_scps import (
    _build_scp_terraform_module,
    _render_account_scp_terraform,
    _render_ou_scp_terraform,
    _render_root_scp_terraform,
    render_scp_terraform,
)


def make_org_empty() -> OrganizationHierarchy:
    return OrganizationHierarchy(root_id="r-root", organizational_units={}, accounts={})


def test_render_scp_terraform_no_recommendations(tmp_path: Path) -> None:
    """
    Nothing to place is a plan for an empty directory, not a no-op.

    The caller applies this empty plan and deletes whatever a previous run
    left behind.
    """
    org = make_org_empty()

    assert render_scp_terraform([], org, tmp_path) == {}
    assert not any(tmp_path.iterdir())


def test_render_scp_terraform_warn_missing_account(tmp_path: Path) -> None:
    org = make_org_empty()
    rec = SCPPlacementRecommendations(
        check_name="deny_ec2_imds_v1",
        recommended_level="account",
        target_ou_id=None,
        affected_accounts=["999999999999"],
        compliance_percentage=100.0,
        reasoning="test",
    )

    # Should raise exception for missing account
    with pytest.raises(RuntimeError, match="Account \\(999999999999\\) not found in organization hierarchy"):
        render_scp_terraform([rec], org, tmp_path)


def test_render_scp_terraform_warn_missing_ou(tmp_path: Path) -> None:
    org = make_org_empty()
    rec = SCPPlacementRecommendations(
        check_name="deny_ec2_imds_v1",
        recommended_level="ou",
        target_ou_id="ou-unknown",
        affected_accounts=[],
        compliance_percentage=100.0,
        reasoning="test",
    )

    # Should raise exception for missing OU
    with pytest.raises(RuntimeError, match="OU ou-unknown not found in organization hierarchy"):
        render_scp_terraform([rec], org, tmp_path)


def test_make_safe_variable_name_edge_cases() -> None:
    assert make_safe_variable_name("My  Name--X") == "my_name_x"
    assert make_safe_variable_name("a__b---c  d") == "a_b_c_d"
    # Starts with digit -> prefixed
    assert make_safe_variable_name("123bad-name") == "ou_123bad_name"


def test_build_scp_terraform_module_output_format() -> None:
    """Test exact output format with section comments and proper blank line spacing."""
    org = make_org_empty()
    recs = [
        SCPPlacementRecommendations(
            check_name="deny_ec2_imds_v1",
            recommended_level="root",
            target_ou_id=None,
            affected_accounts=[],
            compliance_percentage=100.0,
            reasoning="test",
        ),
        SCPPlacementRecommendations(
            check_name="deny_rds_unencrypted",
            recommended_level="root",
            target_ou_id=None,
            affected_accounts=[],
            compliance_percentage=100.0,
            reasoning="test",
        ),
    ]
    result = _build_scp_terraform_module(
        module_name="scps_test_ou",
        target_id_reference="local.test_ou_id",
        recommendations=recs,
        comment="Test OU",
        organization_hierarchy=org
    )

    expected = '''# Code generated by Headroom. DO NOT EDIT.
# Auto-generated SCP Terraform configuration for Test OU
# Generated by Headroom based on compliance analysis

module "scps_test_ou" {
  source = "../modules/scps"
  target_id = local.test_ou_id

  # EC2
  deny_ec2_ami_owner = false
  deny_ec2_imds_hop_limit = false
  deny_ec2_imds_v1 = true
  deny_ec2_public_ip = false

  # EKS
  deny_eks_create_cluster_without_tag = false

  # IAM
  deny_iam_saml_provider_not_aws_sso = false
  deny_iam_user_creation = false

  # Lambda
  deny_lambda_auth_type_none = false

  # RDS
  deny_rds_unencrypted = true
}
'''
    assert result == expected


# Tests for _build_scp_terraform_module()
def test_build_scp_terraform_module_single_check_100_percent_compliant() -> None:
    """Should include SCP flag when compliance is 100%."""
    org = make_org_empty()
    rec = SCPPlacementRecommendations(
        check_name="deny_ec2_imds_v1",
        recommended_level="root",
        target_ou_id=None,
        affected_accounts=[],
        compliance_percentage=100.0,
        reasoning="test",
    )
    result = _build_scp_terraform_module(
        module_name="scps_root",
        target_id_reference="local.root_ou_id",
        recommendations=[rec],
        comment="Organization Root",
        organization_hierarchy=org
    )
    assert "deny_ec2_imds_v1 = true" in result
    assert "deny_iam_user_creation = false" in result
    assert "deny_iam_saml_provider_not_aws_sso = false" in result
    assert "deny_rds_unencrypted = false" in result
    assert "iam_allowed_users" not in result
    assert 'module "scps_root"' in result
    assert "target_id = local.root_ou_id" in result
    # Verify section comments are present
    assert "  # EC2" in result
    assert "  # EKS" in result
    assert "  # IAM" in result
    assert "  # RDS" in result
    # Verify blank lines separate sections (not '  #' lines)
    assert "  #\n" not in result, "Should not have '  #' comment lines, only blank lines for spacing"


def test_build_scp_terraform_module_multiple_checks_all_compliant() -> None:
    """Should include all SCP flags when all checks are 100% compliant."""
    org = make_org_empty()
    recs = [
        SCPPlacementRecommendations(
            check_name="deny_ec2_imds_v1",
            recommended_level="root",
            target_ou_id=None,
            affected_accounts=[],
            compliance_percentage=100.0,
            reasoning="test",
        ),
        SCPPlacementRecommendations(
            check_name="deny_iam_user_creation",
            recommended_level="root",
            target_ou_id=None,
            affected_accounts=[],
            compliance_percentage=100.0,
            reasoning="test",
            allowlist_values=["arn:aws:iam::111111111111:user/terraform-user"],
        ),
    ]
    result = _build_scp_terraform_module(
        module_name="scps_test",
        target_id_reference="local.test_id",
        recommendations=recs,
        comment="Test",
        organization_hierarchy=org
    )
    assert "deny_ec2_imds_v1 = true" in result
    assert "deny_iam_user_creation = true" in result
    assert "deny_iam_saml_provider_not_aws_sso = false" in result
    assert "deny_rds_unencrypted = false" in result
    assert "arn:aws:iam::111111111111:user/terraform-user" in result


def test_build_scp_terraform_module_renders_iam_allowed_users() -> None:
    """Should include IAM user ARNs with account ID replaced by local variable reference."""
    org = OrganizationHierarchy(
        root_id="r-root",
        organizational_units={},
        accounts={
            "111111111111": AccountOrgPlacement(
                account_id="111111111111",
                account_name="test-account-1",
                parent_ou_id="ou-test",
                ou_path=["r-root", "ou-test"]
            ),
            "222222222222": AccountOrgPlacement(
                account_id="222222222222",
                account_name="test-account-2",
                parent_ou_id="ou-test",
                ou_path=["r-root", "ou-test"]
            )
        }
    )
    recs = [
        SCPPlacementRecommendations(
            check_name="deny_iam_user_creation",
            recommended_level="root",
            target_ou_id=None,
            affected_accounts=[],
            compliance_percentage=100.0,
            reasoning="test",
            allowlist_values=[
                "arn:aws:iam::111111111111:user/terraform-user",
                "arn:aws:iam::222222222222:user/github-actions"
            ]
        ),
    ]
    result = _build_scp_terraform_module(
        module_name="scps_test",
        target_id_reference="local.test_id",
        recommendations=recs,
        comment="Test",
        organization_hierarchy=org
    )
    assert "deny_iam_user_creation = true" in result
    assert "deny_iam_saml_provider_not_aws_sso = false" in result
    assert "iam_allowed_users = [" in result
    assert '"arn:aws:iam::${local.test_account_1_account_id}:user/terraform-user",' in result
    assert '"arn:aws:iam::${local.test_account_2_account_id}:user/github-actions",' in result


def test_build_scp_terraform_module_escapes_an_iam_user_path() -> None:
    """
    An IAM path admits any printable ASCII character, so a path can hold the
    `${` that opens an interpolation. It is data, and the account reference
    beside it is the one live piece of template text in the ARN.
    """
    org = OrganizationHierarchy(
        root_id="r-root",
        organizational_units={},
        accounts={
            "111111111111": AccountOrgPlacement(
                account_id="111111111111",
                account_name="test-account-1",
                parent_ou_id="ou-test",
                ou_path=["r-root", "ou-test"]
            ),
        }
    )
    recs = [
        SCPPlacementRecommendations(
            check_name="deny_iam_user_creation",
            recommended_level="root",
            target_ou_id=None,
            affected_accounts=[],
            compliance_percentage=100.0,
            reasoning="test",
            allowlist_values=['arn:aws:iam::111111111111:user/${team}/"deploy"'],
        ),
    ]
    result = _build_scp_terraform_module(
        module_name="scps_test",
        target_id_reference="local.test_id",
        recommendations=recs,
        comment="Test",
        organization_hierarchy=org
    )
    assert '"arn:aws:iam::${local.test_account_1_account_id}:user/$${team}/\\"deploy\\"",' in result


def test_build_scp_terraform_module_iam_allowed_users_unknown_account() -> None:
    """Should keep ARN unchanged when account ID is not in organization hierarchy."""
    org = OrganizationHierarchy(
        root_id="r-root",
        organizational_units={},
        accounts={
            "111111111111": AccountOrgPlacement(
                account_id="111111111111",
                account_name="test-account-1",
                parent_ou_id="ou-test",
                ou_path=["r-root", "ou-test"]
            )
        }
    )
    recs = [
        SCPPlacementRecommendations(
            check_name="deny_iam_user_creation",
            recommended_level="root",
            target_ou_id=None,
            affected_accounts=[],
            compliance_percentage=100.0,
            reasoning="test",
            allowlist_values=[
                "arn:aws:iam::111111111111:user/terraform-user",
                "arn:aws:iam::999999999999:user/unknown-account"
            ]
        ),
    ]
    result = _build_scp_terraform_module(
        module_name="scps_test",
        target_id_reference="local.test_id",
        recommendations=recs,
        comment="Test",
        organization_hierarchy=org
    )
    assert "deny_iam_user_creation = true" in result
    assert "deny_iam_saml_provider_not_aws_sso = false" in result
    assert "iam_allowed_users = [" in result
    assert '"arn:aws:iam::${local.test_account_1_account_id}:user/terraform-user",' in result
    assert '"arn:aws:iam::999999999999:user/unknown-account",' in result


def test_build_scp_terraform_module_rejects_a_none_level_recommendation() -> None:
    """
    A "none" recommendation is not a placement and must never reach a module.

    Placement emits it when no account is safe, and the grouping step drops
    it before any module is built. Arriving here means that step was
    bypassed, which would enable a policy for accounts that violate it.
    """
    org = make_org_empty()
    none_rec = SCPPlacementRecommendations(
        check_name="deny_ec2_imds_v1",
        recommended_level="none",
        target_ou_id=None,
        affected_accounts=[],
        compliance_percentage=0.0,
        reasoning="test",
    )
    with pytest.raises(RuntimeError, match=r"scps_root.*deny_ec2_imds_v1.*'none'"):
        _build_scp_terraform_module(
            module_name="scps_root",
            target_id_reference="local.root_ou_id",
            recommendations=[none_rec],
            comment="Organization Root",
            organization_hierarchy=org
        )


def test_build_scp_terraform_module_leaves_unrecommended_checks_false() -> None:
    """A check with no recommendation for this module stays off."""
    org = make_org_empty()
    rec = SCPPlacementRecommendations(
        check_name="deny_ec2_imds_v1",
        recommended_level="root",
        target_ou_id=None,
        affected_accounts=[],
        compliance_percentage=100.0,
        reasoning="test",
    )
    result = _build_scp_terraform_module(
        module_name="scps_root",
        target_id_reference="local.root_ou_id",
        recommendations=[rec],
        comment="Organization Root",
        organization_hierarchy=org
    )
    assert "deny_ec2_imds_v1 = true" in result
    assert "deny_iam_user_creation = false" in result
    assert "deny_iam_saml_provider_not_aws_sso = false" in result
    assert "iam_allowed_users" not in result
    assert 'module "scps_root"' in result


def test_build_scp_terraform_module_enables_every_recommendation_it_is_given() -> None:
    """
    A recommendation reaching a module IS the signal to enable its policy.

    `affected_accounts` is the zero-violation subset at every level, so there
    is nothing left to re-check here. Generation used to gate on
    `compliance_percentage == 100.0`, a value root and OU recommendations
    hardcode and account recommendations can never reach - see
    test_account_level_recommendation_enables_its_policy.
    """
    org = make_org_empty()
    recs = [
        SCPPlacementRecommendations(
            check_name="deny_ec2_imds_v1",
            recommended_level="root",
            target_ou_id=None,
            affected_accounts=[],
            compliance_percentage=100.0,
            reasoning="test",
        ),
        SCPPlacementRecommendations(
            check_name="deny_iam_user_creation",
            recommended_level="root",
            target_ou_id=None,
            affected_accounts=[],
            compliance_percentage=100.0,
            reasoning="test",
            allowlist_values=["arn:aws:iam::111111111111:user/terraform-user"],
        ),
    ]
    result = _build_scp_terraform_module(
        module_name="scps_root",
        target_id_reference="local.root_ou_id",
        recommendations=recs,
        comment="Organization Root",
        organization_hierarchy=org
    )
    assert "deny_ec2_imds_v1 = true" in result
    assert "deny_iam_user_creation = true" in result
    assert "deny_iam_saml_provider_not_aws_sso = false" in result


def test_build_scp_terraform_module_rejects_an_unregistered_check() -> None:
    """
    A recommendation for a check no definition describes aborts the render.

    The registered name is the Terraform parameter, so there is nothing left
    to normalize here. Generation used to rewrite hyphens to underscores,
    which silently accepted `deny-ec2-imds-v1` as `deny_ec2_imds_v1` - and
    just as silently rendered a module missing the statement whenever the
    name was wrong in any other way.
    """
    org = make_org_empty()
    rec = SCPPlacementRecommendations(
        check_name="deny-ec2-imds-v1",
        recommended_level="root",
        target_ou_id=None,
        affected_accounts=[],
        compliance_percentage=100.0,
        reasoning="test",
    )

    with pytest.raises(RuntimeError, match="was given a recommendation for deny-ec2-imds-v1"):
        _build_scp_terraform_module(
            module_name="scps_root",
            target_id_reference="local.root_ou_id",
            recommendations=[rec],
            comment="Organization Root",
            organization_hierarchy=org
        )


def make_rec(
    check_name: str = "deny_ec2_imds_v1",
    level: str = "root",
    target_ou_id: str | None = None,
    affected_accounts: list[str] | None = None,
    allowlist_values: list[str] | None = None,
) -> SCPPlacementRecommendations:
    return SCPPlacementRecommendations(
        check_name=check_name,
        recommended_level=level,
        target_ou_id=target_ou_id,
        affected_accounts=affected_accounts if affected_accounts is not None else [],
        compliance_percentage=100.0,
        reasoning="test",
        allowlist_values=allowlist_values if allowlist_values is not None else [],
    )


# Tests for _render_account_scp_terraform()
def test_render_account_scp_terraform_names_the_file_for_the_account() -> None:
    org = OrganizationHierarchy(
        root_id="r-root",
        organizational_units={},
        accounts={
            "333333333333": AccountOrgPlacement(
                account_id="333333333333",
                account_name="Test Account",
                parent_ou_id="ou-test",
                ou_path=["r-root", "ou-test"]
            )
        }
    )
    rec = make_rec(level="account", affected_accounts=["333333333333"])
    output_path = Path("/nonexistent")

    filepath, content = _render_account_scp_terraform(
        "333333333333", [rec], org, output_path
    )

    # Rendering touches no filesystem, so a directory that does not exist is fine.
    assert filepath == output_path / "test_account_scps.tf"
    assert "scps_test_account" in content
    assert "local.test_account_account_id" in content
    assert "deny_ec2_imds_v1 = true" in content
    assert "deny_iam_saml_provider_not_aws_sso = false" in content


def test_render_account_scp_terraform_rejects_a_folded_name_collision() -> None:
    """
    Two account names that fold alike abort rather than overwrite.

    The plan is a dict keyed on the path, so without this the second account's
    file silently replaces the first's while the plan is still being built --
    render-before-mutate never sees a conflict, and one account ships with no
    SCPs at all.

    Only one of the two accounts is being rendered here. The guard has to read
    the whole hierarchy, because the account it collides with may be one this
    run was never asked to generate for.
    """
    org = OrganizationHierarchy(
        root_id="r-root",
        organizational_units={},
        accounts={
            "111111111111": AccountOrgPlacement(
                account_id="111111111111",
                account_name="Prod-US",
                parent_ou_id="ou-test",
                ou_path=["r-root", "ou-test"]
            ),
            "222222222222": AccountOrgPlacement(
                account_id="222222222222",
                account_name="Prod US",
                parent_ou_id="ou-test",
                ou_path=["r-root", "ou-test"]
            ),
        }
    )
    rec = make_rec(level="account", affected_accounts=["111111111111"])

    with pytest.raises(RuntimeError, match="prod_us"):
        _render_account_scp_terraform(
            "111111111111", [rec], org, Path("/nonexistent")
        )


def test_render_account_scp_terraform_raises_error_for_missing_account() -> None:
    org = make_org_empty()
    rec = make_rec(level="account", affected_accounts=["999999999999"])

    with pytest.raises(RuntimeError, match="Account \\(999999999999\\) not found in organization hierarchy"):
        _render_account_scp_terraform("999999999999", [rec], org, Path("/nonexistent"))


# Tests for _render_ou_scp_terraform()
def test_render_ou_scp_terraform_names_the_file_for_the_ou() -> None:
    org = OrganizationHierarchy(
        root_id="r-root",
        organizational_units={
            "ou-test": OrganizationalUnit(
                ou_id="ou-test",
                name="Test OU",
                parent_ou_id="r-root",
                child_ous=[],
                accounts=[]
            )
        },
        accounts={}
    )
    rec = make_rec(level="ou", target_ou_id="ou-test")
    output_path = Path("/nonexistent")

    filepath, content = _render_ou_scp_terraform("ou-test", [rec], org, output_path)

    assert filepath == output_path / "test_ou_ou_scps.tf"
    assert "scps_test_ou_ou" in content
    assert "local.test_ou_ou_id" in content
    assert "deny_ec2_imds_v1 = true" in content
    assert "deny_iam_saml_provider_not_aws_sso = false" in content


def test_render_ou_scp_terraform_raises_error_for_missing_ou() -> None:
    org = make_org_empty()
    rec = make_rec(level="ou", target_ou_id="ou-missing")

    with pytest.raises(RuntimeError, match="OU ou-missing not found in organization hierarchy"):
        _render_ou_scp_terraform("ou-missing", [rec], org, Path("/nonexistent"))


# Tests for _render_root_scp_terraform()
def test_render_root_scp_terraform_renders_root_scps_tf() -> None:
    org = make_org_empty()
    output_path = Path("/nonexistent")

    filepath, content = _render_root_scp_terraform([make_rec()], org, output_path)

    assert filepath == output_path / "root_scps.tf"
    assert "scps_root" in content
    assert "local.root_ou_id" in content
    assert "deny_ec2_imds_v1 = true" in content
    assert "deny_iam_saml_provider_not_aws_sso = false" in content


def test_render_root_scp_terraform_multiple_checks() -> None:
    org = make_org_empty()
    recs = [
        make_rec(),
        make_rec(
            check_name="deny_iam_user_creation",
            allowlist_values=["arn:aws:iam::111111111111:user/terraform-user"],
        ),
    ]

    _, content = _render_root_scp_terraform(recs, org, Path("/nonexistent"))

    assert "deny_ec2_imds_v1 = true" in content
    assert "deny_iam_user_creation = true" in content
    assert "deny_iam_saml_provider_not_aws_sso = false" in content
    assert "deny_rds_unencrypted = false" in content
    assert "arn:aws:iam::111111111111:user/terraform-user" in content


def test_render_root_scp_terraform_includes_saml_guardrail() -> None:
    org = make_org_empty()
    rec = make_rec(check_name="deny_iam_saml_provider_not_aws_sso")

    _, content = _render_root_scp_terraform([rec], org, Path("/nonexistent"))

    assert "deny_ec2_imds_v1 = false" in content
    assert "deny_iam_user_creation = false" in content
    assert "deny_iam_saml_provider_not_aws_sso = true" in content
    assert "deny_rds_unencrypted = false" in content


# Tests for the plan a run produces
def test_plan_omits_root_when_nothing_is_placed_there(tmp_path: Path) -> None:
    """
    No root recommendation means no root file in the plan.

    Reconciliation deletes what the plan omits, so this is what removes a
    root_scps.tf left behind by a run that did place a policy there.
    """
    org = OrganizationHierarchy(
        root_id="r-root",
        organizational_units={
            "ou-test": OrganizationalUnit(
                ou_id="ou-test",
                name="Test OU",
                parent_ou_id="r-root",
                child_ous=[],
                accounts=[]
            )
        },
        accounts={}
    )
    rec = make_rec(level="ou", target_ou_id="ou-test")

    plan = render_scp_terraform([rec], org, tmp_path)

    assert set(plan) == {tmp_path / "test_ou_ou_scps.tf"}
    assert not (tmp_path / "root_scps.tf").exists()


def test_an_account_named_root_does_not_take_the_root_policy_file(tmp_path: Path) -> None:
    """
    'Root' reduces to `root`, which is already the root policy file's name.

    make_account_base_names keeps accounts apart from each other, and
    make_ou_base_names keeps OUs apart from each other and from `root`.
    Neither sees this one: the account namespace and the fixed root filename
    only meet at the path, which is where claim_plan_path compares them.

    Left unguarded the root policy silently becomes the account's, or the
    account's becomes the root policy, depending on which is rendered second.
    """
    org = OrganizationHierarchy(
        root_id="r-root",
        organizational_units={},
        accounts={
            "111111111111": AccountOrgPlacement(
                account_id="111111111111",
                account_name="Root",
                parent_ou_id=None,
                ou_path=["r-root"]
            )
        }
    )
    recommendations = [
        make_rec(level="root"),
        make_rec(level="account", affected_accounts=["111111111111"]),
    ]

    with pytest.raises(RuntimeError, match="root_scps.tf"):
        render_scp_terraform(recommendations, org, tmp_path)


def test_render_scp_terraform_returns_the_rendered_content_by_destination(
    tmp_path: Path
) -> None:
    org = make_org_empty()

    rendered = render_scp_terraform([make_rec()], org, tmp_path)

    assert set(rendered) == {tmp_path / "root_scps.tf"}
    assert "deny_ec2_imds_v1 = true" in rendered[tmp_path / "root_scps.tf"]


def test_a_failed_render_raises_before_any_file_is_produced(tmp_path: Path) -> None:
    """
    A late failure must not leave a partial mapping for the caller to apply.

    The plan is rendered in full before anything is written, so the OU whose
    render succeeds never reaches the returned mapping when a later one fails.
    """
    org = OrganizationHierarchy(
        root_id="r-root",
        organizational_units={
            "ou-test": OrganizationalUnit(
                ou_id="ou-test",
                name="Test OU",
                parent_ou_id="r-root",
                child_ous=[],
                accounts=[]
            )
        },
        accounts={}
    )
    good = make_rec(level="ou", target_ou_id="ou-test")
    doomed = make_rec(level="account", affected_accounts=["999999999999"])

    with pytest.raises(RuntimeError, match="not found in organization hierarchy"):
        render_scp_terraform([good, doomed], org, tmp_path)


def test_render_scp_terraform_raises_when_an_account_collides_with_root(tmp_path: Path) -> None:
    """
    An account named `root` renders to root_scps.tf, the root file's own name.

    The SCP renderer takes accounts before root, so the account claims the
    filename first and the root render is the one that raises. Either order
    must abort rather than let one silently overwrite the other.
    """
    org = OrganizationHierarchy(
        root_id="r-1111",
        organizational_units={},
        accounts={
            "111111111111": AccountOrgPlacement(
                account_id="111111111111",
                account_name="root",
                parent_ou_id=None,
                ou_path=["r-1111"]
            )
        }
    )
    account_rec = make_rec(level="account", affected_accounts=["111111111111"])
    root_rec = make_rec(level="root")

    with pytest.raises(RuntimeError, match="root_scps.tf"):
        render_scp_terraform([account_rec, root_rec], org, tmp_path)

    assert not any(tmp_path.iterdir())


def test_build_scp_terraform_module_with_ec2_ami_owner_check_with_allowed_owners() -> None:
    """Should include ec2_allowed_ami_owners when deny_ec2_ami_owner is enabled."""
    org = make_org_empty()
    rec = SCPPlacementRecommendations(
        check_name="deny_ec2_ami_owner",
        recommended_level="root",
        target_ou_id=None,
        affected_accounts=[],
        compliance_percentage=100.0,
        reasoning="test",
        allowlist_values=["amazon", "aws-marketplace"]
    )
    result = _build_scp_terraform_module(
        module_name="scps_root",
        target_id_reference="local.root_ou_id",
        recommendations=[rec],
        comment="Organization Root",
        organization_hierarchy=org
    )
    assert "deny_ec2_ami_owner = true" in result
    assert '"amazon"' in result
    assert '"aws-marketplace"' in result
    assert "ec2_allowed_ami_owners = [" in result


def test_build_scp_terraform_module_ec2_ami_owner_empty_allowlist_stays_off() -> None:
    """
    An empty AMI owner allowlist turns the policy off rather than rendering.

    `ec2_allowed_ami_owners = []` denies every ec2:RunInstances call instead
    of denying none of them, so it is never a safe thing to emit. It arises
    whenever no instance in the covered accounts had a resolvable AMI owner,
    which an account with no EC2 instances at all reaches placement as. That
    is a fact about those accounts rather than a broken run: the module says
    so and generation continues. A result file predating AMI owner collection
    is the other cause, and parsing rejects that before reaching here.
    """
    org = make_org_empty()
    rec = SCPPlacementRecommendations(
        check_name="deny_ec2_ami_owner",
        recommended_level="root",
        target_ou_id=None,
        affected_accounts=[],
        compliance_percentage=100.0,
        reasoning="test",
        allowlist_values=[],
    )
    result = _build_scp_terraform_module(
        module_name="scps_root",
        target_id_reference="local.root_ou_id",
        recommendations=[rec],
        comment="Organization Root",
        organization_hierarchy=org
    )

    assert "deny_ec2_ami_owner = false" in result
    assert "ec2_allowed_ami_owners" not in result
    assert "no instance in the accounts this module covers" in result


def test_account_level_recommendation_enables_its_policy() -> None:
    """
    An account-level recommendation enables the policy in that account's file.

    Account placement only happens when at least one OTHER account violates
    the check, so an account recommendation's org-wide coverage is below 100%
    by construction. Generation used to read that fraction as the safety
    signal, which made every per-account file emit every policy as false -
    the whole tier produced nothing but disabled policies.
    """
    org = OrganizationHierarchy(
        root_id="r-root",
        organizational_units={},
        accounts={
            "111111111111": AccountOrgPlacement(
                "111111111111", "safe-account", "r-root", ["Root"]
            ),
        },
    )
    rec = SCPPlacementRecommendations(
        check_name="deny_ec2_imds_v1",
        recommended_level="account",
        target_ou_id=None,
        affected_accounts=["111111111111"],
        compliance_percentage=100.0,
        reasoning="Only 1 out of 3 accounts have zero violations - deploy at individual account level",
    )
    result = _build_scp_terraform_module(
        module_name="scps_safe_account",
        target_id_reference="local.safe_account_account_id",
        recommendations=[rec],
        comment="Account: safe-account",
        organization_hierarchy=org
    )

    assert "deny_ec2_imds_v1 = true" in result


def _synthetic_allowlist_values(
    definition: CheckDefinition,
    observed_nothing: Sequence[str],
) -> Optional[List[str]]:
    """
    Give one definition the allowlist values that let it render enabled.

    The guard reads the boolean, not the values, so any one value will do.
    What matters is that every definition declaring an allowlist gets one
    without an entry being written for it here, so a new allowlist check is
    guarded the day it is registered (INV-13). A check named in
    `observed_nothing` gets the empty list instead, which is what an
    allowlist check whose covered accounts observed nothing carries.

    Args:
        definition: The check being placed
        observed_nothing: Allowlist checks to hand an empty list

    Returns:
        None for a check with no allowlist, otherwise its values
    """
    if definition.allowlist is None:
        return None
    if definition.check_name in observed_nothing:
        return []
    return ["observed-value"]


def _render_every_scp_check(observed_nothing: Sequence[str] = ()) -> str:
    """
    Render one module in which every registered SCP check is safe to enable.

    Two checks turn themselves off when their allowlist would be empty
    (INV-06), so an allowlist check needs observed values before it will
    render enabled. With an empty list the module renders it `false` for a
    stated reason, which is correct behavior and useless as a guard;
    `observed_nothing` lets a test reproduce that stated-reason `false` on
    demand.

    Args:
        observed_nothing: Allowlist checks whose covered accounts observed nothing

    Returns:
        The rendered Terraform module block
    """
    org = OrganizationHierarchy(
        root_id="r-1111",
        organizational_units={},
        accounts={
            "111111111111": AccountOrgPlacement(
                account_id="111111111111",
                account_name="acme-co",
                parent_ou_id="r-1111",
                ou_path=["Root"],
            ),
        },
    )
    recommendations = [
        SCPPlacementRecommendations(
            check_name=definition.check_name,
            recommended_level="root",
            target_ou_id=None,
            affected_accounts=[],
            compliance_percentage=100.0,
            reasoning="test",
            allowlist_values=_synthetic_allowlist_values(definition, observed_nothing),
        )
        for definition in get_check_definitions("scps")
    ]

    return _build_scp_terraform_module(
        module_name="scps_root",
        target_id_reference="local.root_ou_id",
        recommendations=recommendations,
        comment="Organization Root",
        organization_hierarchy=org,
    )


def _unrendered_scp_checks(observed_nothing: Sequence[str] = ()) -> List[str]:
    """
    Report the registered SCP checks the renderer does not enable.

    Reads the value, not just the name. `deny_x = false` written as a literal
    is indistinguishable in the output from a check that was collected,
    parsed, placed, and then dropped at render - which is the omission this
    guard exists to catch.

    Args:
        observed_nothing: Allowlist checks whose covered accounts observed nothing

    Returns:
        Registered SCP check names that did not render as enabled
    """
    rendered = _render_every_scp_check(observed_nothing)

    return [
        check_name for check_name in get_check_names("scps")
        if f"{check_name} = true" not in rendered
    ]


def test_every_registered_scp_check_is_rendered() -> None:
    """
    A registered SCP check must reach the Terraform module.

    _build_scp_terraform_module renders from get_check_definitions("scps"), so
    a check the generator has never heard of reaches the module - which is
    what test_a_registered_scp_check_renders_without_a_generator_edit pins.
    This one covers the checks that are actually registered: a check dropped
    at render is collected, written, parsed, and placed, and nothing else in
    the suite notices. The module renders, Terraform validates, and the
    operator sees a policy that is simply missing a statement.

    This is the SCP counterpart of test_every_registered_rcp_check_is_rendered
    (INV-13).
    """
    assert _unrendered_scp_checks() == []


def test_the_unrendered_check_guard_reads_the_rendered_value() -> None:
    """
    A check that renders `false` must fail the guard, not satisfy it.

    Matching "<name> = " and stopping there accepts `deny_x = false` written
    as a literal, which is indistinguishable in the output from a check that
    was collected, parsed, placed, and then dropped. Giving
    deny_iam_user_creation an observed-empty allowlist reproduces exactly
    that: INV-06 still emits its parameter, just as `false` under an
    explanatory comment, so a guard matching only the name reports nothing
    wrong.
    """
    assert _unrendered_scp_checks(observed_nothing=["deny_iam_user_creation"]) == ["deny_iam_user_creation"]


def test_a_registered_scp_check_renders_without_a_generator_edit(
    monkeypatch: pytest.MonkeyPatch
) -> None:
    """
    A check the generator has never heard of renders from its definition.

    Registering a check is meant to be the whole of wiring it into the
    generated module (INV-13). A tenth check is collected, written, parsed,
    and placed, so the only place it can still be silently dropped is here.
    The assertion pins its boolean between its alphabetical neighbour and the
    next section comment, which is what proves it rendered in the position
    its definition asks for rather than appended anywhere at all.
    """
    org = make_org_empty()
    monkeypatch.setitem(
        _CHECK_REGISTRY,
        "deny_ec2_unrendered",
        CheckDefinition(
            check_class=DenyEc2PublicIpCheck,
            check_name="deny_ec2_unrendered",
            check_type="scps",
            terraform_section=TerraformSection.EC2,
            allowlist=None,
        ),
    )
    rec = SCPPlacementRecommendations(
        check_name="deny_ec2_unrendered",
        recommended_level="root",
        target_ou_id=None,
        affected_accounts=[],
        compliance_percentage=100.0,
        reasoning="test",
    )

    result = _build_scp_terraform_module(
        module_name="scps_root",
        target_id_reference="local.root_ou_id",
        recommendations=[rec],
        comment="Organization Root",
        organization_hierarchy=org,
    )

    assert "  deny_ec2_public_ip = false\n  deny_ec2_unrendered = true\n\n  # EKS" in result


def test_the_render_guard_covers_a_new_allowlist_check_without_an_edit(
    monkeypatch: pytest.MonkeyPatch
) -> None:
    """
    An allowlist check registered tomorrow is guarded today.

    The guard once carried a hand-written table of the values each allowlist
    check needs before it renders enabled, so a new allowlist check reached
    the guard with no values at all, and the renderer's "carries None" error
    stood in for the guard's own verdict. The values now come from the
    definition, so the guard names the check when the renderer drops it and
    stays quiet when it does not - here, when it does not.
    """
    monkeypatch.setitem(
        _CHECK_REGISTRY,
        "deny_ec2_unrendered_allowlisted",
        CheckDefinition(
            check_class=DenyEc2PublicIpCheck,
            check_name="deny_ec2_unrendered_allowlisted",
            check_type="scps",
            terraform_section=TerraformSection.EC2,
            allowlist=Allowlist(
                summary_key="unique_widgets",
                terraform_variable="ec2_allowed_widgets",
                empty_allowlist_comment="No widgets observed",
            ),
        ),
    )

    assert _unrendered_scp_checks() == []


def test_build_scp_terraform_module_iam_user_creation_empty_allowlist_stays_off() -> None:
    """
    An empty IAM user allowlist turns the policy off rather than rendering.

    `iam_allowed_users = []` renders `NotResource: []`. A policy array takes
    one or more values, so Organizations rejects the document at apply time and
    the whole SCP fails to attach - taking the other statements in the module
    down with it, not just this one. The covered accounts holding no IAM user
    is an ordinary fact about them, so the module says so and generation
    continues (INV-06).
    """
    org = make_org_empty()
    rec = SCPPlacementRecommendations(
        check_name="deny_iam_user_creation",
        recommended_level="root",
        target_ou_id=None,
        affected_accounts=[],
        compliance_percentage=100.0,
        reasoning="test",
        allowlist_values=[],
    )
    result = _build_scp_terraform_module(
        module_name="scps_root",
        target_id_reference="local.root_ou_id",
        recommendations=[rec],
        comment="Organization Root",
        organization_hierarchy=org
    )

    assert "deny_iam_user_creation = false" in result
    assert "iam_allowed_users" not in result
    assert "no IAM user in the accounts this module covers" in result


def test_build_scp_terraform_module_iam_user_creation_renders_a_populated_allowlist() -> None:
    """The guard must not fire when the accounts did hold users."""
    org = make_org_empty()
    rec = SCPPlacementRecommendations(
        check_name="deny_iam_user_creation",
        recommended_level="root",
        target_ou_id=None,
        affected_accounts=[],
        compliance_percentage=100.0,
        reasoning="test",
        allowlist_values=["arn:aws:iam::111111111111:user/breakglass"],
    )
    result = _build_scp_terraform_module(
        module_name="scps_root",
        target_id_reference="local.root_ou_id",
        recommendations=[rec],
        comment="Organization Root",
        organization_hierarchy=org
    )

    assert "deny_iam_user_creation = true" in result
    assert "arn:aws:iam::111111111111:user/breakglass" in result
