"""
Tests for Terraform data models.

Tests the TerraformParameter, TerraformComment, and TerraformModule dataclasses
used for structured Terraform generation.
"""


from headroom.terraform.models import TerraformModule, TerraformParameter, TerraformComment


class TestTerraformParameter:
    """Tests for TerraformParameter class."""

    def test_render_boolean_true(self) -> None:
        """Test rendering boolean true value."""
        param = TerraformParameter("enabled", True)
        assert param.render() == "  enabled = true"

    def test_render_boolean_false(self) -> None:
        """Test rendering boolean false value."""
        param = TerraformParameter("enabled", False)
        assert param.render() == "  enabled = false"

    def test_render_string(self) -> None:
        """Test rendering string value."""
        param = TerraformParameter("name", "test-name")
        assert param.render() == '  name = "test-name"'

    def test_render_empty_string(self) -> None:
        """Test rendering empty string value."""
        param = TerraformParameter("description", "")
        assert param.render() == '  description = ""'

    def test_render_empty_list(self) -> None:
        """Test rendering empty list."""
        param = TerraformParameter("items", [])
        assert param.render() == "  items = []"

    def test_render_single_item_list(self) -> None:
        """Test rendering list with single item."""
        param = TerraformParameter("accounts", ["123456789012"])
        expected = '  accounts = [\n    "123456789012",\n  ]'
        assert param.render() == expected

    def test_render_multi_item_list(self) -> None:
        """Test rendering list with multiple items."""
        param = TerraformParameter("accounts", ["123456789012", "234567890123", "345678901234"])
        expected = '  accounts = [\n    "123456789012",\n    "234567890123",\n    "345678901234",\n  ]'
        assert param.render() == expected

    def test_render_integer(self) -> None:
        """Test rendering integer value."""
        param = TerraformParameter("count", 42)
        assert param.render() == "  count = 42"

    def test_render_float(self) -> None:
        """Test rendering float value."""
        param = TerraformParameter("percentage", 99.5)
        assert param.render() == "  percentage = 99.5"

    def test_render_with_special_characters(self) -> None:
        """Test rendering string with special characters."""
        param = TerraformParameter("arn", "arn:aws:iam::123456789012:user/path/username")
        assert param.render() == '  arn = "arn:aws:iam::123456789012:user/path/username"'

    def test_render_with_terraform_variable(self) -> None:
        """Test rendering string containing Terraform variable reference."""
        param = TerraformParameter("account_id", "${local.account_id}")
        assert param.render() == '  account_id = "${local.account_id}"'


class TestTerraformComment:
    """Tests for TerraformComment class."""

    def test_render_simple_comment(self) -> None:
        """Test rendering simple comment."""
        comment = TerraformComment("EC2")
        assert comment.render() == "  # EC2"

    def test_render_empty_comment(self) -> None:
        """Test rendering empty comment creates blank line."""
        comment = TerraformComment("")
        assert comment.render() == ""

    def test_render_multiword_comment(self) -> None:
        """Test rendering comment with multiple words."""
        comment = TerraformComment("OpenSearch Serverless")
        assert comment.render() == "  # OpenSearch Serverless"

    def test_render_comment_with_special_chars(self) -> None:
        """Test rendering comment with special characters."""
        comment = TerraformComment("IAM (Identity & Access Management)")
        assert comment.render() == "  # IAM (Identity & Access Management)"


class TestTerraformModule:
    """Tests for TerraformModule class."""

    def test_render_minimal_module(self) -> None:
        """Test rendering module with no parameters or comment."""
        module = TerraformModule(
            name="test_module",
            source="../modules/test",
            target_id="local.test_id",
            parameters=[]
        )
        expected = '''module "test_module" {
  source = "../modules/test"
  target_id = local.test_id

}
'''
        assert module.render() == expected

    def test_render_module_with_comment(self) -> None:
        """Test rendering module with comment."""
        module = TerraformModule(
            name="test_module",
            source="../modules/test",
            target_id="local.test_id",
            parameters=[],
            comment="Test Environment"
        )
        expected = '''# Auto-generated SCP Terraform configuration for Test Environment
# Generated by Headroom based on compliance analysis

module "test_module" {
  source = "../modules/test"
  target_id = local.test_id

}
'''
        assert module.render() == expected

    def test_render_module_with_single_parameter(self) -> None:
        """Test rendering module with single parameter."""
        module = TerraformModule(
            name="test_module",
            source="../modules/test",
            target_id="local.test_id",
            parameters=[TerraformParameter("enabled", True)]
        )
        expected = '''module "test_module" {
  source = "../modules/test"
  target_id = local.test_id

  enabled = true
}
'''
        assert module.render() == expected

    def test_render_module_with_multiple_parameters(self) -> None:
        """Test rendering module with multiple parameters."""
        module = TerraformModule(
            name="test_module",
            source="../modules/test",
            target_id="local.test_id",
            parameters=[
                TerraformParameter("enabled", True),
                TerraformParameter("name", "test-name"),
                TerraformParameter("count", 5),
            ]
        )
        expected = '''module "test_module" {
  source = "../modules/test"
  target_id = local.test_id

  enabled = true
  name = "test-name"
  count = 5
}
'''
        assert module.render() == expected

    def test_render_module_with_list_parameter(self) -> None:
        """Test rendering module with list parameter."""
        module = TerraformModule(
            name="scps_root",
            source="../modules/scps",
            target_id="local.root_ou_id",
            parameters=[
                TerraformParameter("deny_ec2_ami_owner", True),
                TerraformParameter("allowed_ami_owners", ["123456789012", "234567890123"]),
            ],
            comment="Organization Root"
        )
        expected = '''# Auto-generated SCP Terraform configuration for Organization Root
# Generated by Headroom based on compliance analysis

module "scps_root" {
  source = "../modules/scps"
  target_id = local.root_ou_id

  deny_ec2_ami_owner = true
  allowed_ami_owners = [
    "123456789012",
    "234567890123",
  ]
}
'''
        assert module.render() == expected

    def test_render_module_with_comments(self) -> None:
        """Test rendering module with section comments and blank lines."""
        module = TerraformModule(
            name="test_module",
            source="../modules/test",
            target_id="local.test_id",
            parameters=[
                TerraformComment("EC2"),
                TerraformParameter("deny_ec2_ami_owner", True),
                TerraformComment(""),
                TerraformComment("IAM"),
                TerraformParameter("deny_iam_user_creation", False),
            ]
        )
        expected = '''module "test_module" {
  source = "../modules/test"
  target_id = local.test_id

  # EC2
  deny_ec2_ami_owner = true

  # IAM
  deny_iam_user_creation = false
}
'''
        assert module.render() == expected

    def test_render_module_with_empty_list(self) -> None:
        """Test rendering module with empty list parameter."""
        module = TerraformModule(
            name="test_module",
            source="../modules/test",
            target_id="local.test_id",
            parameters=[
                TerraformParameter("enabled", True),
                TerraformParameter("items", []),
            ]
        )
        expected = '''module "test_module" {
  source = "../modules/test"
  target_id = local.test_id

  enabled = true
  items = []
}
'''
        assert module.render() == expected

    def test_render_module_with_complex_parameters(self) -> None:
        """
        Test rendering module with all parameter types.

        This represents a realistic SCP module configuration.
        """
        module = TerraformModule(
            name="scps_security_tooling_ou",
            source="../modules/scps",
            target_id="local.top_level_security_tooling_ou_id",
            parameters=[
                TerraformParameter("deny_ec2_ami_owner", True),
                TerraformParameter("allowed_ami_owners", ["123456789012"]),
                TerraformParameter("deny_ec2_imds_v1", False),
                TerraformParameter("deny_eks_create_cluster_without_tag", True),
                TerraformParameter("deny_iam_user_creation", True),
                TerraformParameter("allowed_iam_users", []),
                TerraformParameter("deny_rds_unencrypted", True),
            ],
            comment="OU Security Tooling"
        )

        result = module.render()

        assert 'module "scps_security_tooling_ou" {' in result
        assert 'source = "../modules/scps"' in result
        assert "target_id = local.top_level_security_tooling_ou_id" in result
        assert "deny_ec2_ami_owner = true" in result
        assert '"123456789012"' in result
        assert "deny_ec2_imds_v1 = false" in result
        assert "deny_eks_create_cluster_without_tag = true" in result
        assert "deny_iam_user_creation = true" in result
        assert "allowed_iam_users = []" in result
        assert "deny_rds_unencrypted = true" in result
        assert "# Auto-generated SCP Terraform configuration for OU Security Tooling" in result

    def test_render_rcp_module(self) -> None:
        """
        Test rendering RCP module configuration.

        This represents a realistic RCP module configuration.
        """
        module = TerraformModule(
            name="rcps_root",
            source="../modules/rcps",
            target_id="local.root_ou_id",
            parameters=[
                TerraformParameter("deny_ecr_third_party_access", True),
                TerraformParameter("deny_ecr_third_party_access_account_ids_allowlist", ["123456789012", "234567890123"]),
                TerraformParameter("enforce_assume_role_org_identities", True),
                TerraformParameter("deny_sts_third_party_assumerole_account_ids_allowlist", ["123456789012"]),
                TerraformParameter("deny_aoss_third_party_access", False),
                TerraformParameter("deny_s3_third_party_access", True),
                TerraformParameter("third_party_s3_access_account_ids_allowlist", ["123456789012"]),
            ],
            comment="Organization Root",
            policy_type="RCP"
        )

        result = module.render()

        assert 'module "rcps_root" {' in result
        assert 'source = "../modules/rcps"' in result
        assert "target_id = local.root_ou_id" in result
        assert "deny_ecr_third_party_access = true" in result
        assert "deny_ecr_third_party_access_account_ids_allowlist" in result
        assert "enforce_assume_role_org_identities = true" in result
        assert "deny_aoss_third_party_access = false" in result
        assert "deny_s3_third_party_access = true" in result
        assert "# Auto-generated RCP Terraform configuration for Organization Root" in result
        assert "# Generated by Headroom based on third-party account analysis" in result


class TestTerraformParameterEdgeCases:
    """Test edge cases for TerraformParameter."""

    def test_render_with_quotes_in_string(self) -> None:
        """Test rendering string containing quotes (no escaping done)."""
        param = TerraformParameter("description", 'test "value"')
        assert param.render() == '  description = "test "value""'

    def test_render_zero_value(self) -> None:
        """Test rendering zero integer value."""
        param = TerraformParameter("count", 0)
        assert param.render() == "  count = 0"

    def test_render_negative_number(self) -> None:
        """Test rendering negative number."""
        param = TerraformParameter("offset", -5)
        assert param.render() == "  offset = -5"

    def test_render_list_with_empty_strings(self) -> None:
        """Test rendering list containing empty strings."""
        param = TerraformParameter("values", ["", "test", ""])
        expected = '  values = [\n    "",\n    "test",\n    "",\n  ]'
        assert param.render() == expected


class TestTerraformModuleEdgeCases:
    """Test edge cases for TerraformModule."""

    def test_render_with_quoted_target_id(self) -> None:
        """Test module with quoted target_id reference."""
        module = TerraformModule(
            name="test_module",
            source="../modules/test",
            target_id='"test-account-id"',
            parameters=[]
        )
        result = module.render()
        assert 'target_id = "test-account-id"' in result

    def test_render_with_special_chars_in_name(self) -> None:
        """Test module with special characters in name."""
        module = TerraformModule(
            name="test_module_123",
            source="../modules/test",
            target_id="local.test_id",
            parameters=[]
        )
        result = module.render()
        assert 'module "test_module_123"' in result

    def test_render_empty_comment(self) -> None:
        """Test module with empty string comment (should be treated as no comment)."""
        module = TerraformModule(
            name="test_module",
            source="../modules/test",
            target_id="local.test_id",
            parameters=[],
            comment=""
        )
        result = module.render()
        assert "# Auto-generated" not in result
