"""
Tests for terraform.reconcile module.

Covers which files Headroom claims as its own, which it must never touch, and
what a reconcile pass deletes.
"""

import logging
from pathlib import Path

import pytest

from headroom.constants import GENERATED_MARKER
from headroom.terraform.generate_scps import generate_scp_terraform
from headroom.terraform.reconcile import (
    find_managed_files,
    reconcile_generated_terraform,
)
from headroom.types import (
    AccountOrgPlacement,
    OrganizationHierarchy,
    OrganizationalUnit,
    SCPPlacementRecommendations,
)


def write_generated(path: Path, body: str = 'module "x" {}\n') -> Path:
    """Write a file carrying the marker Headroom stamps on its own output."""
    path.write_text(f"{GENERATED_MARKER}\n{body}")
    return path


def test_find_managed_files_claims_marked_terraform(tmp_path: Path) -> None:
    marked = write_generated(tmp_path / "root_scps.tf")

    assert find_managed_files(tmp_path) == {marked}


def test_find_managed_files_leaves_hand_written_terraform_alone(tmp_path: Path) -> None:
    # A file named exactly like ours but written by a person. Ownership is the
    # marker, never the filename - this is the case a filename glob deletes.
    (tmp_path / "custom_scps.tf").write_text('module "custom" {}\n')

    assert find_managed_files(tmp_path) == set()


def test_find_managed_files_only_considers_terraform(tmp_path: Path) -> None:
    # test_environment/scps/README.md opens with "All of these files are
    # auto-generated by Headroom." A substring scan over every file deletes it.
    (tmp_path / "README.md").write_text(
        f"All of these files are auto-generated by Headroom.\n{GENERATED_MARKER}\n"
    )

    assert find_managed_files(tmp_path) == set()


def test_find_managed_files_requires_the_marker_on_the_first_line(tmp_path: Path) -> None:
    (tmp_path / "late.tf").write_text(f"# something else\n{GENERATED_MARKER}\n")

    assert find_managed_files(tmp_path) == set()


def test_find_managed_files_never_claims_a_symlink(tmp_path: Path) -> None:
    # rcps/grab_org_info.tf is a symlink into scps/. Following it would read a
    # marked file and delete the link.
    real = write_generated(tmp_path / "grab_org_info.tf")
    link_dir = tmp_path / "rcps"
    link_dir.mkdir()
    (link_dir / "grab_org_info.tf").symlink_to(real)

    assert find_managed_files(link_dir) == set()


def test_find_managed_files_ignores_directories(tmp_path: Path) -> None:
    (tmp_path / "modules.tf").mkdir()

    assert find_managed_files(tmp_path) == set()


def test_find_managed_files_ignores_empty_file(tmp_path: Path) -> None:
    (tmp_path / "empty.tf").write_text("")

    assert find_managed_files(tmp_path) == set()


def test_find_managed_files_ignores_undecodable_file(tmp_path: Path) -> None:
    (tmp_path / "binary.tf").write_bytes(b"\xff\xfe\x00\x01")

    assert find_managed_files(tmp_path) == set()


def test_find_managed_files_missing_directory_is_empty(tmp_path: Path) -> None:
    assert find_managed_files(tmp_path / "absent") == set()


def test_reconcile_deletes_managed_file_absent_from_the_plan(tmp_path: Path) -> None:
    stale = write_generated(tmp_path / "acme_ou_scps.tf")
    kept = write_generated(tmp_path / "root_scps.tf")

    deleted = reconcile_generated_terraform([tmp_path], {kept})

    assert deleted == [stale]
    assert not stale.exists()
    assert kept.exists()


def test_reconcile_with_an_empty_plan_deletes_every_managed_file(tmp_path: Path) -> None:
    first = write_generated(tmp_path / "root_scps.tf")
    second = write_generated(tmp_path / "acme_ou_scps.tf")

    deleted = reconcile_generated_terraform([tmp_path], set())

    assert deleted == sorted([first, second])
    assert not any(p.exists() for p in (first, second))


def test_reconcile_leaves_unmanaged_files_untouched(tmp_path: Path) -> None:
    readme = tmp_path / "README.md"
    readme.write_text("All of these files are auto-generated by Headroom.\n")
    provider = tmp_path / "provider.tf"
    provider.write_text('provider "aws" {}\n')

    assert reconcile_generated_terraform([tmp_path], set()) == []
    assert readme.exists()
    assert provider.exists()


def test_reconcile_spans_every_directory_it_is_given(tmp_path: Path) -> None:
    scps = tmp_path / "scps"
    rcps = tmp_path / "rcps"
    scps.mkdir()
    rcps.mkdir()
    stale_scp = write_generated(scps / "root_scps.tf")
    stale_rcp = write_generated(rcps / "root_rcps.tf")

    deleted = reconcile_generated_terraform([scps, rcps], set())

    assert deleted == sorted([stale_scp, stale_rcp])


def test_reconcile_logs_every_deletion(
    tmp_path: Path,
    caplog: pytest.LogCaptureFixture,
) -> None:
    stale = write_generated(tmp_path / "acme_ou_scps.tf")

    with caplog.at_level(logging.INFO, logger="headroom.terraform.reconcile"):
        reconcile_generated_terraform([tmp_path], set())

    assert str(stale) in caplog.text


def test_reconcile_dry_run_reports_without_deleting(tmp_path: Path) -> None:
    stale = write_generated(tmp_path / "acme_ou_scps.tf")

    deleted = reconcile_generated_terraform([tmp_path], set(), dry_run=True)

    assert deleted == [stale]
    assert stale.exists()


# End-to-end convergence: generate, then reconcile against what was generated.
# These are the scenarios that motivated reconciliation - each one leaves a file
# deploying a policy the current run did not ask for.
def org_with_one_ou() -> OrganizationHierarchy:
    return OrganizationHierarchy(
        root_id="r-root",
        organizational_units={
            "ou-test": OrganizationalUnit(
                ou_id="ou-test",
                name="Test OU",
                parent_ou_id="r-root",
                child_ous=[],
                accounts=["333333333333"],
            )
        },
        accounts={
            "333333333333": AccountOrgPlacement(
                account_id="333333333333",
                account_name="Test Account",
                parent_ou_id="ou-test",
                ou_path=["r-root", "ou-test"],
            )
        },
    )


def scp_rec(
    level: str,
    target_ou_id: str | None = None,
    affected_accounts: list[str] | None = None,
) -> SCPPlacementRecommendations:
    return SCPPlacementRecommendations(
        check_name="deny-ec2-imds-v1",
        recommended_level=level,
        target_ou_id=target_ou_id,
        affected_accounts=affected_accounts if affected_accounts is not None else [],
        compliance_percentage=100.0,
        reasoning="test",
    )


def run(recommendations: list[SCPPlacementRecommendations], out: Path) -> None:
    """Generate, then reconcile the directory against what was generated."""
    plan = generate_scp_terraform(recommendations, org_with_one_ou(), str(out))
    reconcile_generated_terraform([out], set(plan))


def test_moving_a_policy_from_root_to_an_account_drops_the_root_attachment(
    tmp_path: Path
) -> None:
    run([scp_rec("root")], tmp_path)
    assert (tmp_path / "root_scps.tf").exists()

    run([scp_rec("account", affected_accounts=["333333333333"])], tmp_path)

    assert not (tmp_path / "root_scps.tf").exists()
    assert "deny_ec2_imds_v1 = true" in (tmp_path / "test_account_scps.tf").read_text()


def test_an_ou_losing_its_recommendation_loses_its_file(tmp_path: Path) -> None:
    run([scp_rec("ou", target_ou_id="ou-test")], tmp_path)
    assert (tmp_path / "test_ou_ou_scps.tf").exists()

    # The check moves down to the account, which is what happens when another
    # account under the OU starts violating it. The OU-wide attachment must go,
    # or it keeps denying the account that just proved it cannot take the policy.
    run([scp_rec("account", affected_accounts=["333333333333"])], tmp_path)

    assert not (tmp_path / "test_ou_ou_scps.tf").exists()


def test_a_run_that_places_nothing_removes_every_managed_file(tmp_path: Path) -> None:
    run(
        [scp_rec("root"), scp_rec("ou", target_ou_id="ou-test")],
        tmp_path,
    )
    assert len(list(tmp_path.glob("*.tf"))) == 2

    run([], tmp_path)

    assert list(tmp_path.glob("*.tf")) == []


def test_reconciliation_leaves_everything_it_did_not_write(tmp_path: Path) -> None:
    readme = tmp_path / "README.md"
    readme.write_text("All of these files are auto-generated by Headroom.\n")
    handwritten = tmp_path / "provider.tf"
    handwritten.write_text('provider "aws" {}\n')
    run([scp_rec("root")], tmp_path)

    run([], tmp_path)

    assert not (tmp_path / "root_scps.tf").exists()
    assert readme.exists()
    assert handwritten.exists()
