"""
Tests for terraform.generate_scps module.

Covers early returns, warnings for missing targets, and name normalization edges.
"""

from pathlib import Path

import pytest

from headroom.types import (
    AccountOrgPlacement,
    OrganizationHierarchy,
    OrganizationalUnit,
    SCPPlacementRecommendations,
)
from headroom.terraform import make_safe_variable_name
from headroom.terraform.generate_scps import (
    _build_scp_terraform_module,
    _generate_account_scp_terraform,
    _generate_ou_scp_terraform,
    _generate_root_scp_terraform,
    generate_scp_terraform,
)


def make_org_empty() -> OrganizationHierarchy:
    return OrganizationHierarchy(root_id="r-root", organizational_units={}, accounts={})


def test_generate_scp_terraform_no_recommendations(tmp_path: Path) -> None:
    org = make_org_empty()

    generate_scp_terraform([], org, str(tmp_path))
    assert not any(tmp_path.iterdir())


def test_generate_scp_terraform_warn_missing_account(tmp_path: Path) -> None:
    org = make_org_empty()
    rec = SCPPlacementRecommendations(
        check_name="deny-ec2-imds-v1",
        recommended_level="account",
        target_ou_id=None,
        affected_accounts=["999999999999"],
        compliance_percentage=100.0,
        reasoning="test",
    )

    # Should raise exception for missing account
    with pytest.raises(RuntimeError, match="Account \\(999999999999\\) not found in organization hierarchy"):
        generate_scp_terraform([rec], org, str(tmp_path))


def test_generate_scp_terraform_warn_missing_ou(tmp_path: Path) -> None:
    org = make_org_empty()
    rec = SCPPlacementRecommendations(
        check_name="deny-ec2-imds-v1",
        recommended_level="ou",
        target_ou_id="ou-unknown",
        affected_accounts=[],
        compliance_percentage=100.0,
        reasoning="test",
    )

    # Should raise exception for missing OU
    with pytest.raises(RuntimeError, match="OU ou-unknown not found in organization hierarchy"):
        generate_scp_terraform([rec], org, str(tmp_path))


def test_make_safe_variable_name_edge_cases() -> None:
    assert make_safe_variable_name("My  Name--X") == "my_name_x"
    assert make_safe_variable_name("a__b---c  d") == "a_b_c_d"
    # Starts with digit -> prefixed
    assert make_safe_variable_name("123bad-name") == "ou_123bad_name"


def test_build_scp_terraform_module_output_format() -> None:
    """Test exact output format with section comments and proper blank line spacing."""
    org = make_org_empty()
    recs = [
        SCPPlacementRecommendations(
            check_name="deny-ec2-imds-v1",
            recommended_level="root",
            target_ou_id=None,
            affected_accounts=[],
            compliance_percentage=100.0,
            reasoning="test",
        ),
        SCPPlacementRecommendations(
            check_name="deny-rds-unencrypted",
            recommended_level="root",
            target_ou_id=None,
            affected_accounts=[],
            compliance_percentage=100.0,
            reasoning="test",
        ),
    ]
    result = _build_scp_terraform_module(
        module_name="scps_test_ou",
        target_id_reference="local.test_ou_id",
        recommendations=recs,
        comment="Test OU",
        organization_hierarchy=org
    )

    expected = '''# Auto-generated SCP Terraform configuration for Test OU
# Generated by Headroom based on compliance analysis

module "scps_test_ou" {
  source = "../modules/scps"
  target_id = local.test_ou_id

  # EC2
  deny_ec2_ami_owner = false
  deny_ec2_imds_hop_limit = false
  deny_ec2_imds_v1 = true
  deny_ec2_public_ip = false

  # EKS
  deny_eks_create_cluster_without_tag = false

  # IAM
  deny_iam_saml_provider_not_aws_sso = false
  deny_iam_user_creation = false

  # Lambda
  deny_lambda_auth_type_none = false

  # RDS
  deny_rds_unencrypted = true
}
'''
    assert result == expected


# Tests for _build_scp_terraform_module()
def test_build_scp_terraform_module_single_check_100_percent_compliant() -> None:
    """Should include SCP flag when compliance is 100%."""
    org = make_org_empty()
    rec = SCPPlacementRecommendations(
        check_name="deny-ec2-imds-v1",
        recommended_level="root",
        target_ou_id=None,
        affected_accounts=[],
        compliance_percentage=100.0,
        reasoning="test",
    )
    result = _build_scp_terraform_module(
        module_name="scps_root",
        target_id_reference="local.root_ou_id",
        recommendations=[rec],
        comment="Organization Root",
        organization_hierarchy=org
    )
    assert "deny_ec2_imds_v1 = true" in result
    assert "deny_iam_user_creation = false" in result
    assert "deny_iam_saml_provider_not_aws_sso = false" in result
    assert "deny_rds_unencrypted = false" in result
    assert "iam_allowed_users" not in result
    assert 'module "scps_root"' in result
    assert "target_id = local.root_ou_id" in result
    # Verify section comments are present
    assert "  # EC2" in result
    assert "  # EKS" in result
    assert "  # IAM" in result
    assert "  # RDS" in result
    # Verify blank lines separate sections (not '  #' lines)
    assert "  #\n" not in result, "Should not have '  #' comment lines, only blank lines for spacing"


def test_build_scp_terraform_module_multiple_checks_all_compliant() -> None:
    """Should include all SCP flags when all checks are 100% compliant."""
    org = make_org_empty()
    recs = [
        SCPPlacementRecommendations(
            check_name="deny-ec2-imds-v1",
            recommended_level="root",
            target_ou_id=None,
            affected_accounts=[],
            compliance_percentage=100.0,
            reasoning="test",
        ),
        SCPPlacementRecommendations(
            check_name="deny-iam-user-creation",
            recommended_level="root",
            target_ou_id=None,
            affected_accounts=[],
            compliance_percentage=100.0,
            reasoning="test",
        ),
    ]
    result = _build_scp_terraform_module(
        module_name="scps_test",
        target_id_reference="local.test_id",
        recommendations=recs,
        comment="Test",
        organization_hierarchy=org
    )
    assert "deny_ec2_imds_v1 = true" in result
    assert "deny_iam_user_creation = true" in result
    assert "deny_iam_saml_provider_not_aws_sso = false" in result
    assert "deny_rds_unencrypted = false" in result
    assert "iam_allowed_users = []" in result


def test_build_scp_terraform_module_with_iam_user_arns() -> None:
    """Should include IAM user ARNs with account ID replaced by local variable reference."""
    org = OrganizationHierarchy(
        root_id="r-root",
        organizational_units={},
        accounts={
            "111111111111": AccountOrgPlacement(
                account_id="111111111111",
                account_name="test-account-1",
                parent_ou_id="ou-test",
                ou_path=["r-root", "ou-test"]
            ),
            "222222222222": AccountOrgPlacement(
                account_id="222222222222",
                account_name="test-account-2",
                parent_ou_id="ou-test",
                ou_path=["r-root", "ou-test"]
            )
        }
    )
    recs = [
        SCPPlacementRecommendations(
            check_name="deny-iam-user-creation",
            recommended_level="root",
            target_ou_id=None,
            affected_accounts=[],
            compliance_percentage=100.0,
            reasoning="test",
            allowed_iam_user_arns=[
                "arn:aws:iam::111111111111:user/terraform-user",
                "arn:aws:iam::222222222222:user/github-actions"
            ]
        ),
    ]
    result = _build_scp_terraform_module(
        module_name="scps_test",
        target_id_reference="local.test_id",
        recommendations=recs,
        comment="Test",
        organization_hierarchy=org
    )
    assert "deny_iam_user_creation = true" in result
    assert "deny_iam_saml_provider_not_aws_sso = false" in result
    assert "iam_allowed_users = [" in result
    assert '"arn:aws:iam::${local.test_account_1_account_id}:user/terraform-user",' in result
    assert '"arn:aws:iam::${local.test_account_2_account_id}:user/github-actions",' in result


def test_build_scp_terraform_module_with_iam_user_arns_unknown_account() -> None:
    """Should keep ARN unchanged when account ID is not in organization hierarchy."""
    org = OrganizationHierarchy(
        root_id="r-root",
        organizational_units={},
        accounts={
            "111111111111": AccountOrgPlacement(
                account_id="111111111111",
                account_name="test-account-1",
                parent_ou_id="ou-test",
                ou_path=["r-root", "ou-test"]
            )
        }
    )
    recs = [
        SCPPlacementRecommendations(
            check_name="deny-iam-user-creation",
            recommended_level="root",
            target_ou_id=None,
            affected_accounts=[],
            compliance_percentage=100.0,
            reasoning="test",
            allowed_iam_user_arns=[
                "arn:aws:iam::111111111111:user/terraform-user",
                "arn:aws:iam::999999999999:user/unknown-account"
            ]
        ),
    ]
    result = _build_scp_terraform_module(
        module_name="scps_test",
        target_id_reference="local.test_id",
        recommendations=recs,
        comment="Test",
        organization_hierarchy=org
    )
    assert "deny_iam_user_creation = true" in result
    assert "deny_iam_saml_provider_not_aws_sso = false" in result
    assert "iam_allowed_users = [" in result
    assert '"arn:aws:iam::${local.test_account_1_account_id}:user/terraform-user",' in result
    assert '"arn:aws:iam::999999999999:user/unknown-account",' in result


def test_build_scp_terraform_module_rejects_a_none_level_recommendation() -> None:
    """
    A "none" recommendation is not a placement and must never reach a module.

    Placement emits it when no account is safe, and the grouping step drops
    it before any module is built. Arriving here means that step was
    bypassed, which would enable a policy for accounts that violate it.
    """
    org = make_org_empty()
    none_rec = SCPPlacementRecommendations(
        check_name="deny-ec2-imds-v1",
        recommended_level="none",
        target_ou_id=None,
        affected_accounts=[],
        compliance_percentage=0.0,
        reasoning="test",
    )
    with pytest.raises(RuntimeError, match=r"scps_root.*deny-ec2-imds-v1.*'none'"):
        _build_scp_terraform_module(
            module_name="scps_root",
            target_id_reference="local.root_ou_id",
            recommendations=[none_rec],
            comment="Organization Root",
            organization_hierarchy=org
        )


def test_build_scp_terraform_module_leaves_unrecommended_checks_false() -> None:
    """A check with no recommendation for this module stays off."""
    org = make_org_empty()
    rec = SCPPlacementRecommendations(
        check_name="deny-ec2-imds-v1",
        recommended_level="root",
        target_ou_id=None,
        affected_accounts=[],
        compliance_percentage=100.0,
        reasoning="test",
    )
    result = _build_scp_terraform_module(
        module_name="scps_root",
        target_id_reference="local.root_ou_id",
        recommendations=[rec],
        comment="Organization Root",
        organization_hierarchy=org
    )
    assert "deny_ec2_imds_v1 = true" in result
    assert "deny_iam_user_creation = false" in result
    assert "deny_iam_saml_provider_not_aws_sso = false" in result
    assert "iam_allowed_users" not in result
    assert 'module "scps_root"' in result


def test_build_scp_terraform_module_enables_every_recommendation_it_is_given() -> None:
    """
    A recommendation reaching a module IS the signal to enable its policy.

    `affected_accounts` is the zero-violation subset at every level, so there
    is nothing left to re-check here. Generation used to gate on
    `compliance_percentage == 100.0`, a value root and OU recommendations
    hardcode and account recommendations can never reach - see
    test_account_level_recommendation_enables_its_policy.
    """
    org = make_org_empty()
    recs = [
        SCPPlacementRecommendations(
            check_name="deny-ec2-imds-v1",
            recommended_level="root",
            target_ou_id=None,
            affected_accounts=[],
            compliance_percentage=100.0,
            reasoning="test",
        ),
        SCPPlacementRecommendations(
            check_name="deny-iam-user-creation",
            recommended_level="root",
            target_ou_id=None,
            affected_accounts=[],
            compliance_percentage=100.0,
            reasoning="test",
        ),
    ]
    result = _build_scp_terraform_module(
        module_name="scps_root",
        target_id_reference="local.root_ou_id",
        recommendations=recs,
        comment="Organization Root",
        organization_hierarchy=org
    )
    assert "deny_ec2_imds_v1 = true" in result
    assert "deny_iam_user_creation = true" in result
    assert "deny_iam_saml_provider_not_aws_sso = false" in result


def test_build_scp_terraform_module_check_name_with_hyphens_converts_to_underscores() -> None:
    """Should convert hyphens in check names to underscores for Terraform."""
    org = make_org_empty()
    rec = SCPPlacementRecommendations(
        check_name="deny-ec2-imds-v1",
        recommended_level="root",
        target_ou_id=None,
        affected_accounts=[],
        compliance_percentage=100.0,
        reasoning="test",
    )
    result = _build_scp_terraform_module(
        module_name="scps_root",
        target_id_reference="local.root_ou_id",
        recommendations=[rec],
        comment="Organization Root",
        organization_hierarchy=org
    )
    assert "deny_ec2_imds_v1 = true" in result
    assert "deny_iam_user_creation = false" in result
    assert "deny_iam_saml_provider_not_aws_sso = false" in result
    assert "iam_allowed_users" not in result
    assert "deny-ec2-imds-v1" not in result


# Tests for _generate_account_scp_terraform()
def test_generate_account_scp_terraform_creates_file_with_correct_name() -> None:
    """Should create Terraform file with account name."""
    org = OrganizationHierarchy(
        root_id="r-root",
        organizational_units={},
        accounts={
            "333333333333": AccountOrgPlacement(
                account_id="333333333333",
                account_name="Test Account",
                parent_ou_id="ou-test",
                ou_path=["r-root", "ou-test"]
            )
        }
    )
    rec = SCPPlacementRecommendations(
        check_name="deny-ec2-imds-v1",
        recommended_level="account",
        target_ou_id=None,
        affected_accounts=["333333333333"],
        compliance_percentage=100.0,
        reasoning="test",
    )
    output_path = Path("/tmp/test_scps")
    output_path.mkdir(parents=True, exist_ok=True)

    _generate_account_scp_terraform("333333333333", [rec], org, output_path)

    expected_file = output_path / "test_account_scps.tf"
    assert expected_file.exists()
    content = expected_file.read_text()
    assert "scps_test_account" in content
    assert "local.test_account_account_id" in content
    assert "deny_ec2_imds_v1 = true" in content
    assert "deny_iam_saml_provider_not_aws_sso = false" in content
    expected_file.unlink()


def test_generate_account_scp_terraform_raises_error_for_missing_account() -> None:
    """Should raise RuntimeError when account is not in organization hierarchy."""
    org = make_org_empty()
    rec = SCPPlacementRecommendations(
        check_name="deny-ec2-imds-v1",
        recommended_level="account",
        target_ou_id=None,
        affected_accounts=["999999999999"],
        compliance_percentage=100.0,
        reasoning="test",
    )
    output_path = Path("/tmp/test_scps")

    with pytest.raises(RuntimeError, match="Account \\(999999999999\\) not found in organization hierarchy"):
        _generate_account_scp_terraform("999999999999", [rec], org, output_path)


# Tests for _generate_ou_scp_terraform()
def test_generate_ou_scp_terraform_creates_file_with_correct_name() -> None:
    """Should create Terraform file with OU name."""
    org = OrganizationHierarchy(
        root_id="r-root",
        organizational_units={
            "ou-test": OrganizationalUnit(
                ou_id="ou-test",
                name="Test OU",
                parent_ou_id="r-root",
                child_ous=[],
                accounts=[]
            )
        },
        accounts={}
    )
    rec = SCPPlacementRecommendations(
        check_name="deny-ec2-imds-v1",
        recommended_level="ou",
        target_ou_id="ou-test",
        affected_accounts=[],
        compliance_percentage=100.0,
        reasoning="test",
    )
    output_path = Path("/tmp/test_scps")
    output_path.mkdir(parents=True, exist_ok=True)

    _generate_ou_scp_terraform("ou-test", [rec], org, output_path)

    expected_file = output_path / "test_ou_ou_scps.tf"
    assert expected_file.exists()
    content = expected_file.read_text()
    assert "scps_test_ou_ou" in content
    assert "local.test_ou_ou_id" in content
    assert "deny_ec2_imds_v1 = true" in content
    assert "deny_iam_saml_provider_not_aws_sso = false" in content
    expected_file.unlink()


def test_generate_ou_scp_terraform_raises_error_for_missing_ou() -> None:
    """Should raise RuntimeError when OU is not in organization hierarchy."""
    org = make_org_empty()
    rec = SCPPlacementRecommendations(
        check_name="deny-ec2-imds-v1",
        recommended_level="ou",
        target_ou_id="ou-missing",
        affected_accounts=[],
        compliance_percentage=100.0,
        reasoning="test",
    )
    output_path = Path("/tmp/test_scps")

    with pytest.raises(RuntimeError, match="OU ou-missing not found in organization hierarchy"):
        _generate_ou_scp_terraform("ou-missing", [rec], org, output_path)


# Tests for _generate_root_scp_terraform()
def test_generate_root_scp_terraform_creates_file() -> None:
    """Should create root_scps.tf file with correct content."""
    org = make_org_empty()
    rec = SCPPlacementRecommendations(
        check_name="deny-ec2-imds-v1",
        recommended_level="root",
        target_ou_id=None,
        affected_accounts=[],
        compliance_percentage=100.0,
        reasoning="test",
    )
    output_path = Path("/tmp/test_scps")
    output_path.mkdir(parents=True, exist_ok=True)

    _generate_root_scp_terraform([rec], org, output_path)

    expected_file = output_path / "root_scps.tf"
    assert expected_file.exists()
    content = expected_file.read_text()
    assert "scps_root" in content
    assert "local.root_ou_id" in content
    assert "deny_ec2_imds_v1 = true" in content
    assert "deny_iam_saml_provider_not_aws_sso = false" in content
    expected_file.unlink()


def test_generate_root_scp_terraform_no_recommendations_returns_early() -> None:
    """Should return early and not create file when no recommendations."""
    org = make_org_empty()
    output_path = Path("/tmp/test_scps")
    output_path.mkdir(parents=True, exist_ok=True)

    _generate_root_scp_terraform([], org, output_path)

    expected_file = output_path / "root_scps.tf"
    assert not expected_file.exists()


def test_generate_root_scp_terraform_multiple_checks() -> None:
    """Should include all checks in root_scps.tf."""
    org = make_org_empty()
    recs = [
        SCPPlacementRecommendations(
            check_name="deny-ec2-imds-v1",
            recommended_level="root",
            target_ou_id=None,
            affected_accounts=[],
            compliance_percentage=100.0,
            reasoning="test",
        ),
        SCPPlacementRecommendations(
            check_name="deny-iam-user-creation",
            recommended_level="root",
            target_ou_id=None,
            affected_accounts=[],
            compliance_percentage=100.0,
            reasoning="test",
        ),
    ]
    output_path = Path("/tmp/test_scps")
    output_path.mkdir(parents=True, exist_ok=True)

    _generate_root_scp_terraform(recs, org, output_path)

    expected_file = output_path / "root_scps.tf"
    content = expected_file.read_text()
    assert "deny_ec2_imds_v1 = true" in content
    assert "deny_iam_user_creation = true" in content
    assert "deny_iam_saml_provider_not_aws_sso = false" in content
    assert "deny_rds_unencrypted = false" in content
    assert "iam_allowed_users = []" in content
    expected_file.unlink()


def test_generate_root_scp_terraform_includes_saml_guardrail(tmp_path: Path) -> None:
    """Should set deny_iam_saml_provider_not_aws_sso when recommendation is compliant."""
    org = make_org_empty()
    rec = SCPPlacementRecommendations(
        check_name="deny_iam_saml_provider_not_aws_sso",
        recommended_level="root",
        target_ou_id=None,
        affected_accounts=[],
        compliance_percentage=100.0,
        reasoning="test",
    )
    output_path = Path(tmp_path)
    output_path.mkdir(parents=True, exist_ok=True)

    _generate_root_scp_terraform([rec], org, output_path)

    expected_file = output_path / "root_scps.tf"
    content = expected_file.read_text()
    assert "deny_ec2_imds_v1 = false" in content
    assert "deny_iam_user_creation = false" in content
    assert "deny_iam_saml_provider_not_aws_sso = true" in content
    assert "deny_rds_unencrypted = false" in content
    expected_file.unlink()


def test_build_scp_terraform_module_with_rds_check_enabled() -> None:
    """Should include deny_rds_unencrypted flag when check is enabled."""
    org = make_org_empty()
    rec = SCPPlacementRecommendations(
        check_name="deny-rds-unencrypted",
        recommended_level="root",
        target_ou_id=None,
        affected_accounts=[],
        compliance_percentage=100.0,
        reasoning="test",
    )
    result = _build_scp_terraform_module(
        module_name="scps_root",
        target_id_reference="local.root_ou_id",
        recommendations=[rec],
        comment="Organization Root",
        organization_hierarchy=org
    )
    assert "deny_ec2_imds_v1 = false" in result
    assert "deny_iam_user_creation = false" in result
    assert "deny_iam_saml_provider_not_aws_sso = false" in result
    assert "deny_rds_unencrypted = true" in result
    assert "iam_allowed_users" not in result


def test_build_scp_terraform_module_with_saml_guardrail_enabled() -> None:
    """Should include deny_iam_saml_provider_not_aws_sso flag when check is enabled."""
    org = make_org_empty()
    rec = SCPPlacementRecommendations(
        check_name="deny_iam_saml_provider_not_aws_sso",
        recommended_level="root",
        target_ou_id=None,
        affected_accounts=[],
        compliance_percentage=100.0,
        reasoning="test",
    )
    result = _build_scp_terraform_module(
        module_name="scps_root",
        target_id_reference="local.root_ou_id",
        recommendations=[rec],
        comment="Organization Root",
        organization_hierarchy=org
    )
    assert "deny_ec2_imds_v1 = false" in result
    assert "deny_iam_user_creation = false" in result
    assert "deny_iam_saml_provider_not_aws_sso = true" in result
    assert "deny_rds_unencrypted = false" in result
    assert "iam_allowed_users" not in result


def test_build_scp_terraform_module_with_ec2_ami_owner_check_with_allowed_owners() -> None:
    """Should include ec2_allowed_ami_owners when deny_ec2_ami_owner is enabled."""
    org = make_org_empty()
    rec = SCPPlacementRecommendations(
        check_name="deny-ec2-ami-owner",
        recommended_level="root",
        target_ou_id=None,
        affected_accounts=[],
        compliance_percentage=100.0,
        reasoning="test",
        ec2_allowed_ami_owners=["amazon", "aws-marketplace"]
    )
    result = _build_scp_terraform_module(
        module_name="scps_root",
        target_id_reference="local.root_ou_id",
        recommendations=[rec],
        comment="Organization Root",
        organization_hierarchy=org
    )
    assert "deny_ec2_ami_owner = true" in result
    assert '"amazon"' in result
    assert '"aws-marketplace"' in result
    assert "ec2_allowed_ami_owners = [" in result


def test_build_scp_terraform_module_ec2_ami_owner_empty_allowlist_stays_off() -> None:
    """
    An empty AMI owner allowlist turns the policy off rather than rendering.

    `ec2_allowed_ami_owners = []` denies every ec2:RunInstances call instead
    of denying none of them, so it is never a safe thing to emit. It arises
    whenever no instance in the covered accounts had a resolvable AMI owner,
    which an account with no EC2 instances at all reaches placement as. That
    is a fact about those accounts rather than a broken run: the module says
    so and generation continues. A result file predating AMI owner collection
    is the other cause, and parsing rejects that before reaching here.
    """
    org = make_org_empty()
    rec = SCPPlacementRecommendations(
        check_name="deny-ec2-ami-owner",
        recommended_level="root",
        target_ou_id=None,
        affected_accounts=[],
        compliance_percentage=100.0,
        reasoning="test",
    )
    result = _build_scp_terraform_module(
        module_name="scps_root",
        target_id_reference="local.root_ou_id",
        recommendations=[rec],
        comment="Organization Root",
        organization_hierarchy=org
    )

    assert "deny_ec2_ami_owner = false" in result
    assert "ec2_allowed_ami_owners" not in result
    assert "no instance in the accounts this module covers" in result


def test_account_level_recommendation_enables_its_policy() -> None:
    """
    An account-level recommendation enables the policy in that account's file.

    Account placement only happens when at least one OTHER account violates
    the check, so an account recommendation's org-wide coverage is below 100%
    by construction. Generation used to read that fraction as the safety
    signal, which made every per-account file emit every policy as false -
    the whole tier produced nothing but disabled policies.
    """
    org = OrganizationHierarchy(
        root_id="r-root",
        organizational_units={},
        accounts={
            "111111111111": AccountOrgPlacement(
                "111111111111", "safe-account", "r-root", ["Root"]
            ),
        },
    )
    rec = SCPPlacementRecommendations(
        check_name="deny-ec2-imds-v1",
        recommended_level="account",
        target_ou_id=None,
        affected_accounts=["111111111111"],
        compliance_percentage=100.0,
        reasoning="Only 1 out of 3 accounts have zero violations - deploy at individual account level",
    )
    result = _build_scp_terraform_module(
        module_name="scps_safe_account",
        target_id_reference="local.safe_account_account_id",
        recommendations=[rec],
        comment="Account: safe-account",
        organization_hierarchy=org
    )

    assert "deny_ec2_imds_v1 = true" in result
