"""
Constants module for check names and type mappings.

This module contains check name constants used throughout the Headroom codebase.
"""


# AWS ARN Regex Pattern
# Pattern to extract 12-digit account ID from AWS ARN
# Format: arn:partition:service:region:account-id:resource
#
# The service segment is deliberately unconstrained: a resource policy
# principal can be an STS session ARN (arn:aws:sts::{account}:assumed-role/...)
# as readily as an IAM one, and pinning the segment to `iam` drops the account.
# The partition is matched the same way, so GovCloud and China ARNs resolve.
# The account field is twelve ASCII digits, not Python's `\d`, which also
# accepts the digits of every other script; a condition value is never
# validated by AWS and reaches this pattern as written.
AWS_ARN_ACCOUNT_ID_PATTERN = r'^arn:aws[a-z0-9-]*:[^:]+:[^:]*:([0-9]{12}):'

# EC2 IMDSv2 Exemption Tag
# The tag the deny_ec2_imds_v1 SCP exempts on, via
# aws:RequestTag/ExemptFromIMDSv2 on the RunInstances request.
#
# The scan reads it off the INSTANCE, which is a proxy: the same
# TagSpecifications entry that exempts the launch is what puts the tag on the
# instance it creates. See get_ec2_imds_v1_analysis for what the proxy costs.
#
# The two halves are matched differently, and a scanner has to follow both.
# IAM matches condition key names - including the tag key after the slash -
# without regard to case, so `exemptfromimdsv2` exempts too. The value is
# compared with StringNotEquals, which is case-sensitive, so an instance
# tagged "True" is not exempt to enforcement and must not be reported exempt.
# Measured with RunInstances --dry-run: "true" allows the launch, "True"
# does not.
IMDS_EXEMPTION_TAG_KEY = "ExemptFromIMDSv2"
IMDS_EXEMPTION_TAG_VALUE = "true"

# The paved-road tag deny_eks_create_cluster_without_tag requires. Read by the
# same rule as the IMDS pair above: the key matches without regard to case,
# the value does not. The Terraform module spells both out again; changing
# one here does not change it there.
EKS_PAVED_ROAD_TAG_KEY = "PavedRoad"
EKS_PAVED_ROAD_TAG_VALUE = "true"

# Check name constants

# SCP Checks (alphabetical by service)
# EC2
DENY_EC2_AMI_OWNER = "deny_ec2_ami_owner"
DENY_EC2_IMDS_HOP_LIMIT = "deny_ec2_imds_hop_limit"
DENY_EC2_IMDS_V1 = "deny_ec2_imds_v1"
DENY_EC2_PUBLIC_IP = "deny_ec2_public_ip"
# EKS
DENY_EKS_CREATE_CLUSTER_WITHOUT_TAG = "deny_eks_create_cluster_without_tag"
# IAM
DENY_IAM_USER_CREATION = "deny_iam_user_creation"
# IAM SAML
DENY_IAM_SAML_PROVIDER_NOT_AWS_SSO = "deny_iam_saml_provider_not_aws_sso"
# Lambda
DENY_LAMBDA_AUTH_TYPE_NONE = "deny_lambda_auth_type_none"
# RDS
DENY_RDS_UNENCRYPTED = "deny_rds_unencrypted"

# RCP Checks (alphabetical by service)
# ECR
DENY_ECR_THIRD_PARTY_ACCESS = "deny_ecr_third_party_access"
# KMS
DENY_KMS_THIRD_PARTY_ACCESS = "deny_kms_third_party_access"
# S3
DENY_S3_THIRD_PARTY_ACCESS = "deny_s3_third_party_access"
# Secrets Manager
DENY_SECRETS_MANAGER_THIRD_PARTY_ACCESS = "deny_secrets_manager_third_party_access"
DENY_SERVICE_CONFUSED_DEPUTY = "deny_service_confused_deputy"
# SQS
DENY_SQS_THIRD_PARTY_ACCESS = "deny_sqs_third_party_access"
# STS
DENY_STS_THIRD_PARTY_ASSUMEROLE = "deny_sts_third_party_assumerole"

# The token `_redact_account_ids_from_arns` writes into an ARN's account
# field when `exclude_account_ids` is set, and `_read_declared_allowlist`
# restores the owning account ID over.
REDACTED_ACCOUNT_ID = "REDACTED"

# How `summary.scanned_at` renders the moment a check finished for an account.
#
# The value is for a human reading the file, not for a reader to compare, so it
# is the operator's wall clock rather than an ISO instant: month-day-year, a
# twelve-hour time, and the abbreviation of whatever zone the scanning machine
# is set to. `%-I` drops the hour's leading zero and is a macOS and Linux
# extension; Windows spells it `%#I`.
SCAN_TIMESTAMP_FORMAT = "%m-%d-%Y %-I:%M %p %Z"

# Terraform file generation constants
ORG_INFO_FILENAME = "grab_org_info.tf"

# The first line of every .tf file Headroom writes, and the only thing that
# marks a file as Headroom's to delete.
#
# Ownership lives in the content rather than in the filename or a side manifest.
# A filename glob would claim a hand-written custom_scps.tf; a manifest is state
# that can be lost, at which point every generated file becomes an orphan, or go
# stale, at which point it names files that were never ours. The marker travels
# with the file it describes and cannot disagree with it.
#
# Matched as a whole first line, never as a substring: scps/README.md quotes this
# marker inside a code block while explaining it, so a substring scan deletes the
# document that describes it. The wording follows Go's `// Code generated ... DO NOT EDIT.`
# convention, which exists for exactly this purpose.
GENERATED_MARKER = "# Code generated by Headroom. DO NOT EDIT."
