# Auto-generated SCP Terraform configuration for OU acme_acquisition
# Generated by Headroom based on compliance analysis

module "scps_acme_acquisition_ou" {
  source = "../modules/scps"
  target_id = local.top_level_acme_acquisition_ou_id

  # EC2
  deny_ec2_ami_owner = false
  deny_ec2_imds_v1 = true

  # EKS
  deny_eks_create_cluster_without_tag = false

  # IAM
  deny_iam_user_creation = false
  deny_iam_saml_provider_not_aws_sso = false

  # RDS
  deny_rds_unencrypted = false
}
