# Auto-generated SCP Terraform configuration for OU acme_acquisition
# Generated by Headroom based on compliance analysis

module "scps_acme_acquisition_ou" {
  source = "../modules/scps"
  target_id = local.top_level_acme_acquisition_ou_id

  # EC2
  deny_imds_v1_ec2 = true

  # IAM
  deny_iam_user_creation = false
  deny_saml_provider_not_aws_sso = false

  # RDS
  deny_rds_unencrypted = false
}
