# Auto-generated SCP Terraform configuration for OU high_value_assets
# Generated by Headroom based on compliance analysis

module "scps_high_value_assets_ou" {
  source = "../modules/scps"
  target_id = local.top_level_high_value_assets_ou_id

  # EC2
  deny_imds_v1_ec2 = true

  # EKS
  deny_eks_create_cluster_without_tag = false

  # IAM
  deny_iam_user_creation = false

  # RDS
  deny_rds_unencrypted = true
}
