# Auto-generated SCP Terraform configuration for Organization Root
# Generated by Headroom based on compliance analysis

module "scps_root" {
  source = "../modules/scps"
  target_id = local.root_ou_id

  # third_party_role_access
  third_party_role_access = true
  # deny_imds_v1_ec2
  deny_imds_v1_ec2 = true
}
