# Auto-generated RCP Terraform configuration for acme-co
# Generated by Headroom based on third-party account analysis

module "rcps_acme_co" {
  source = "../modules/rcps"
  target_id = local.acme_co_account_id

  third_party_assumerole_account_ids_allowlist = [
  ]
  enforce_assume_role_org_identities = true
}
