# Auto-generated RCP Terraform configuration for OU acme_acquisition
# Generated by Headroom based on third-party account analysis

module "rcps_acme_acquisition_ou" {
  source = "../modules/rcps"
  target_id = local.top_level_acme_acquisition_ou_id

  # ECR
  deny_ecr_third_party_access = false

  # IAM
  third_party_assumerole_account_ids_allowlist = [
    "749430749651",
  ]
  enforce_assume_role_org_identities = true

  # OpenSearch Serverless
  deny_aoss_third_party_access = false

  # S3
  deny_s3_third_party_access = false
}
