# Auto-generated RCP Terraform configuration for OU acme_acquisition
# Generated by Headroom based on third-party account analysis

module "rcps_acme_acquisition_ou" {
  source = "../modules/rcps"
  target_id = local.top_level_acme_acquisition_ou_id

  # AOSS
  deny_aoss_third_party_access = false

  # ECR
  deny_ecr_third_party_access = false

  # S3
  deny_s3_third_party_access = false

  # STS
  deny_sts_third_party_assumerole = true
  sts_third_party_assumerole_account_ids_allowlist = [
    "749430749651",
  ]
}
