# Auto-generated RCP Terraform configuration for Organization Root
# Generated by Headroom based on compliance analysis

module "rcps_root" {
  source = "../modules/rcps"
  target_id = local.root_ou_id
  third_party_assumerole_account_ids = []
  enforce_assume_role_org_identities = true
}
