# Code generated by Headroom. DO NOT EDIT.
# Auto-generated RCP Terraform configuration for security-tooling
# Generated by Headroom based on third-party account analysis

module "rcps_security_tooling" {
  source = "../modules/rcps"
  target_id = local.security_tooling_account_id

  # ECR
  deny_ecr_third_party_access = false

  # KMS
  deny_kms_third_party_access = false

  # S3
  deny_s3_third_party_access = false

  # Secrets Manager
  deny_secrets_manager_third_party_access = false

  # SQS
  deny_sqs_third_party_access = false

  # STS
  deny_sts_third_party_assumerole = true
  sts_third_party_assumerole_account_ids_allowlist = []

  # Service confused deputy
  deny_service_confused_deputy = false
}
